# Generated by Django 6.0.1 on 2026-09-11 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("creators", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BlogPost",
        ),
    ]
