# Generated by Django 6.0.1 on 2026-09-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creators", "0003_creatorprofile_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creatorprofile",
            name="province",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Beijing", "北京市|Běijīng"),
                    ("Chongqing", "重慶市|Chóngqìng"),
                    ("Shanghai", "上海市|Shànghǎi"),
                    ("Tianjin", "天津市|Tiānjīn"),
                    ("Anhui", "安徽省|Ānhuī"),
                    ("Fujian", "福建省|Fújiàn"),
                    ("Gansu", "甘肅省|Gānsù"),
                    ("Guandong", "廣東省|Guǎngdōng"),
                    ("Guizhou", "貴州省|Guìzhōu"),
                    ("Hainan", "海南省|Hǎinán"),
                    ("Hebei", "河北省|Héběi"),
                    ("Heilongjiang", "黑龍江省|Hēilóngjiāng"),
                    ("Henan", "河南省|Hénán"),
                    ("Hubei", "湖北省|Húběi"),
                    ("Hunan", "湖南省|Húnán"),
                    ("Jiangsu", "江蘇省|Jiāngsū"),
                    ("Jiangxi", "江西省|Jiāngxī"),
                    ("Jilin", "吉林省|Jílín"),
                    ("Liaoning", "遼寧省|Liáoníng"),
                    ("Qinghai", "青海省|Qīnghǎi"),
                    ("Shan(3)xi", "陝西省|Shǎnxī"),
                    ("Shandong", "山東省|Shāndōng"),
                    ("Shan(1)xi", "山西省|Shānxī"),
                    ("Sichuan", "四川省|Sìchuān"),
                    ("Yunnan", "雲南省|Yúnnán"),
                    ("Zhejiang", "浙江省|Zhèjiāng"),
                    ("Guangxi", "廣西壯族自治區|Guǎngxī"),
                    ("Neimenggu", "內蒙古自治區|Nèiměnggǔ"),
                    ("Ningxia", "寧夏回族自治區|Níngxià"),
                    ("Xinjiang", "新疆維吾爾自治區|Xīnjiāng"),
                    ("Xizang", "西藏自治區|Xīzàng"),
                ],
                help_text="Select the province/region where the artisan is based.",
                max_length=50,
            ),
        ),
    ]
