# Generated by Django 6.0.1 on 2026-09-15 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creators", "0004_alter_creatorprofile_province"),
    ]

    operations = [
        migrations.AddField(
            model_name="creatorprofile",
            name="page_template",
            field=models.CharField(
                choices=[
                    ("A", "Banner-Led｜橫幅主導"),
                    ("B", "Portrait-Led｜肖像主導"),
                    ("C", "Text-Led｜文本主導"),
                    ("D", "Custom Premium｜客製精選"),
                ],
                default="C",
                help_text="Which layout template renders this artisan's public page.",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="creatorprofile",
            name="premium_page_published",
            field=models.BooleanField(
                default=False,
                help_text="Only render the custom premium template when True. Otherwise, fall back to the standard layout.",
            ),
        ),
        migrations.AddField(
            model_name="creatorprofile",
            name="premium_page_slug",
            field=models.SlugField(
                blank=True,
                help_text="Human-readable alias for the custom premium template (e.g., 'atelier-lumiere'). The actual template file is named by pk: '<pk>_premium_page.html'.",
                max_length=80,
            ),
        ),
        migrations.AlterField(
            model_name="creatorprofile",
            name="craft_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("calligraphy", "Calligraphy｜書法"),
                    ("ceramics", "Ceramics｜陶瓷"),
                    ("companions", "Companion Creatures｜靈伴生靈"),
                    ("design", "Design｜設計"),
                    ("metalwork", "Metalwork｜金工"),
                    ("painting", "Painting｜繪畫"),
                    ("textile", "Textile｜織繡"),
                    ("woodwork", "Woodwork｜木作"),
                    ("other", "Other｜其他"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="creatorprofile",
            name="province",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Beijing", "北京市|Běijīng"),
                    ("Chongqing", "重慶市|Chóngqìng"),
                    ("Shanghai", "上海市|Shànghǎi"),
                    ("Tianjin", "天津市|Tiānjīn"),
                    ("Anhui", "安徽省|Ānhuī"),
                    ("Fujian", "福建省|Fújiàn"),
                    ("Gansu", "甘肅省|Gānsù"),
                    ("Guandong", "廣東省|Guǎngdōng"),
                    ("Guizhou", "貴州省|Guìzhōu"),
                    ("Hainan", "海南省|Hǎinán"),
                    ("Hebei", "河北省|Héběi"),
                    ("Heilongjiang", "黑龍江省|Hēilóngjiāng"),
                    ("Henan", "河南省|Hénán"),
                    ("Hubei", "湖北省|Húběi"),
                    ("Hunan", "湖南省|Húnán"),
                    ("Jiangsu", "江蘇省|Jiāngsū"),
                    ("Jiangxi", "江西省|Jiāngxī"),
                    ("Jilin", "吉林省|Jílín"),
                    ("Liaoning", "遼寧省|Liáoníng"),
                    ("Qinghai", "青海省|Qīnghǎi"),
                    ("Shan(3)xi", "陝西省|Shǎnxī"),
                    ("Shandong", "山東省|Shāndōng"),
                    ("Shan(1)xi", "山西省|Shānxī"),
                    ("Sichuan", "四川省|Sìchuān"),
                    ("Yunnan", "雲南省|Yúnnán"),
                    ("Zhejiang", "浙江省|Zhèjiāng"),
                    ("Guangxi", "廣西壯族自治區|Guǎngxī"),
                    ("Neimenggu", "內蒙古自治區|Nèiměnggǔ"),
                    ("Ningxia", "寧夏回族自治區|Níngxià"),
                    ("Xinjiang", "新疆維吾爾自治區|Xīnjiāng"),
                    ("Xizang", "西藏自治區|Xīzàng"),
                ],
                max_length=50,
            ),
        ),
    ]
