# Generated by Django 6.0.1 on 2026-09-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creators", "0005_creatorprofile_page_template_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CraftType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("label", models.CharField(max_length=100)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "label"],
            },
        ),
        migrations.AddField(
            model_name="creatorprofile",
            name="craft_types",
            field=models.ManyToManyField(
                blank=True, related_name="artisans", to="creators.crafttype"
            ),
        ),
    ]
