# Generated by Django 6.0.1 on 2026-09-16 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("creators", "0006_crafttype_creatorprofile_craft_types"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="creatorprofile",
            name="craft_type",
        ),
    ]
