# Generated by Django 6.0.1 on 2026-09-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creators", "0007_remove_creatorprofile_craft_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="creatorprofile",
            name="wechat",
        ),
        migrations.AddField(
            model_name="creatorprofile",
            name="wechat_qr",
            field=models.ImageField(
                blank=True,
                help_text="Upload your WeChat QR code image.｜上傳您的微信二維碼圖片。",
                null=True,
                upload_to="creators/wechat_qr/",
            ),
        ),
    ]
