# Generated by Django 6.0.1 on 2026-09-19 13:22

import taggit_selectize.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("creators", "0008_remove_creatorprofile_wechat_and_more"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="creatorprofile",
            name="tags",
            field=taggit_selectize.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
