# Generated by Django 6.0.1 on 2026-09-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creators", "0009_alter_creatorprofile_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creatorprofile",
            name="slug",
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
