# https://www.att.com/support_media/images/pdf/Country_Code_List.pdf
# https://my.ems.com.cn/pcp-web/f/pcp/indexController/quotequery
AREA_CODE = [
    # ('DEFAULT', '🌏'),
    ('', '🌏'),
    ('+93',     'Afghanistan 🇦🇫 +93'),
    ('+355',    'Albania 🇦🇱 +355'),
    ('+213',    'Algeria 🇩🇿 +213'),
    ('+1 684',  'American Samoa 🇦🇸 +1 684'),
    ('+376',    'Andorra 🇦🇩 +376'),
    ('+244',    'Angola 🇦🇴 +244'),
    ('+1 264',  'Anguilla 🇦🇮 +1 264'),
    ('+1 268',  'Antigua and Barbuda 🇦🇬 +1 268'),
    ('+54',     'Argentina 🇦🇷 +54'),
    ('+374',    'Armenia 🇦🇲 +374'),
    ('+297',    'Aruba 🇦🇼 +297'),
    ('+247',    'Ascension Island 🇦🇨 +247'),
    ('+61',     'Australia 🇦🇺 +61'),
    ('+43',     'Austria 🇦🇹 +43'),
    ('+994',    'Azerbaijan 🇦🇿 +994'),
    ('+1 242',  'Bahamas 🇧🇸 +1 242'),
    ('+973',    'Bahrain 🇧🇭 +973'),
    ('+880',    'Bangladesh 🇧🇩 +880'),
    ('+1 246',  'Barbados 🇧🇧 +1 246'),
    ('+375',    'Belarus 🇧🇾 +375'),
    ('+32',     'Belgium 🇧🇪 +32'),
    ('+501',    'Belize 🇧🇿 +501'),
    ('+229',    'Benin 🇧🇯 +229'),
    ('+1 441',  'Bermuda 🇧🇲 +1 441'),
    ('+975',    'Bhutan 🇧🇹 +975'),
    ('+591',    'Bolivia 🇧🇴 +591'),
    ('+387',    'Bosnia and Herzegovina 🇧🇦 +387'),
    ('+267',    'Botswana 🇧🇼 +267'),
    ('+55',     'Brazil 🇧🇷 +55'),
    ('+1 284',  'British Virgin Islands 🇻🇬 +1 284'),
    ('+673',    'Brunei 🇧🇳 +673'),
    ('+359',    'Bulgaria 🇧🇬 +359'),
    ('+226',    'Burkina Faso 🇧🇫 +226'),
    ('+95',     'Burma (Myanmar) 🇲🇲 +95'),
    ('+257',    'Burundi 🇧🇮 +257'),
    ('+855',    'Cambodia 🇰🇭 +855'),
    ('+237',    'Cameroon 🇨🇲 +237'),
    ('+1',      'Canada 🇨🇦 +1'),
    ('+238',    'Cape Verde 🇨🇻 +238'),
    ('+1 345',  'Cayman Islands 🇰🇾 +1 345'),
    ('+236',    'Central African Republic 🇨🇫 +236'),
    ('+235',    'Chad 🇹🇩 +235'),
    ('+56',     'Chile 🇨🇱 +56'),
    ('+86',     'China 🇨🇳 +86'),
    ('+61',     'Christmas Island 🇨🇽 +61'),
    ('+61',     'Cocos (Keeling) Islands 🇨🇨 +61'),
    ('+57',     'Colombia 🇨🇴 +57'),
    ('+269',    'Comoros 🇰🇲 +269'),
    ('+682',    'Cook Islands 🇨🇰 +682'),
    ('+506',    'Costa Rica 🇨🇷 +506'),
    ('+385',    'Croatia 🇭🇷 +385'),
    ('+53',     'Cuba 🇨🇺 +53'),
    ('+599',    'Curaçao (Netherlands Antilles) 🇨🇼 +599'),
    ('+357',    'Cyprus 🇨🇾 +357'),
    ('+420',    'Czech Republic 🇨🇿 +420'),
    ('+243',    'Democratic Republic of the Congo 🇨🇩 +243'),
    ('+45',     'Denmark 🇩🇰 +45'),
    ('+246',    'Diego Garcia 🇩🇬 +246'),
    ('+253',    'Djibouti 🇩🇯 +253'),
    ('+1 767',  'Dominica 🇩🇲 +1 767'),
    ('+1 809',  'Dominican Republic 🇩🇴 +1 809'),
    ('+1 829',  'Dominican Republic 🇩🇴 +1 829'),
    ('+1 849',  'Dominican Republic 🇩🇴 +1 849'),
    ('+593',    'Ecuador 🇪🇨 +593'),
    ('+20',     'Egypt 🇪🇬 +20'),
    ('+503',    'El Salvador 🇸🇻 +503'),
    ('+240',    'Equatorial Guinea 🇬🇶 +240'),
    ('+291',    'Eritrea 🇪🇷 +291'),
    ('+372',    'Estonia 🇪🇪 +372'),
    ('+268',    'Eswatini (Swaziland) 🇸🇿 +268'),
    ('+251',    'Ethiopia 🇪🇹 +251'),
    ('+500',    'Falkland Islands (Malvinas) 🇫🇰 +500'),
    ('+298',    'Faroe Islands 🇫🇴 +298'),
    ('+679',    'Fiji 🇫🇯 +679'),
    ('+358',    'Finland 🇫🇮 +358'),
    ('+33',     'France 🇫🇷 +33'),
    ('+594',    'French Guiana 🇬🇫 +594'),
    ('+689',    'French Polynesia 🇵🇫 +689'),
    ('+241',    'Gabon 🇬🇦 +241'),
    ('+220',    'Gambia 🇬🇲 +220'),
    ('+995',    'Georgia 🇬🇪 +995'),
    ('+49',     'Germany 🇩🇪 +49'),
    ('+233',    'Ghana 🇬🇭 +233'),
    ('+350',    'Gibraltar 🇬🇮 +350'),
    ('+30',     'Greece 🇬🇷 +30'),
    ('+299',    'Greenland 🇬🇱 +299'),
    ('+1 473',  'Grenada 🇬🇩 +1 473'),
    ('+590',    'Guadeloupe 🇬🇵 +590'),
    ('+1 671',  'Guam 🇬🇺 +1 671'),
    ('+502',    'Guatemala 🇬🇹 +502'),
    ('+44 1481','Guernsey 🇬🇹 +44 1481'),
    ('+224',    'Guinea 🇬🇳 +224'),
    ('+245',    'Guinea-Bissau 🇬🇼 +245'),
    ('+592',    'Guyana 🇬🇾 +592'),
    ('+509',    'Haiti 🇭🇹 +509'),
    ('+39',     'Holy See (Vatican City) 🇻🇦 +39'),
    ('+504',    'Honduras 🇭🇳 +504'),
    ('+852',    'Hong Kong 🇭🇰 +852'),
    ('+36',     'Hungary 🇭🇺 +36'),
    ('+354',    'Iceland 🇮🇸 +354'),
    ('+91',     'India 🇮🇳 +91'),
    ('+62',     'Indonesia 🇮🇩 +62'),
    ('+98',     'Iran 🇮🇷 +98'),
    ('+964',    'Iraq 🇮🇶 +964'),
    ('+353',    'Ireland 🇮🇪 +353'),
    ('+44',     'Isle of Man 🇮🇲 +44'),
    ('+972',    'Israel 🇮🇱 +972'),
    ('+39',     'Italy 🇮🇹 +39'),
    ('+225',    "Ivory Coast (Côte d'Ivoire) 🇨🇮 +225"),
    ('+1 876',  'Jamaica 🇯🇲 +1 876'),
    ('+81',     'Japan 🇯🇵 +81'),
    ('+44',     'Jersey 🇯🇪 +44'),
    ('+962',    'Jordan 🇯🇴 +962'),
    ('+7',      'Kazakhstan 🇰🇿 +7'),
    ('+254',    'Kenya 🇰🇪 +254'),
    ('+686',    'Kiribati 🇰🇮 +686'),
    ('+965',    'Kuwait 🇰🇼 +965'),
    ('+996',    'Kyrgyzstan 🇰🇬 +996'),
    ('+856',    'Laos 🇱🇦 +856'),
    ('+371',    'Latvia 🇱🇻 +371'),
    ('+961',    'Lebanon 🇱🇧 +961'),
    ('+266',    'Lesotho 🇱🇸 +266'),
    ('+231',    'Liberia 🇱🇷 +231'),
    ('+218',    'Libya 🇱🇾 +218'),
    ('+423',    'Liechtenstein 🇱🇮 +423'),
    ('+370',    'Lithuania 🇱🇹 +370'),
    ('+352',    'Luxembourg 🇱🇺 +352'),
    ('+853',    'Macao SAR 🇲🇴 +853'),
    ('+261',    'Madagascar 🇲🇬 +261'),
    ('+265',    'Malawi 🇲🇼 +265'),
    ('+60',     'Malaysia 🇲🇾 +60'),
    ('+960',    'Maldives 🇲🇻 +960'),
    ('+223',    'Mali 🇲🇱 +223'),
    ('+356',    'Malta 🇲🇹 +356'),
    ('+692',    'Marshall Islands 🇲🇭 +692'),
    ('+596',    'Martinique 🇲🇶 +596'),
    ('+222',    'Mauritania 🇲🇷 +222'),
    ('+230',    'Mauritius 🇲🇺 +230'),
    ('+262',    'Mayotte 🇾🇹 +262'),
    ('+52',     'Mexico 🇲🇽 +52'),
    ('+691',    'Micronesia 🇫🇲 +691'),
    ('+373',    'Moldova 🇲🇩 +373'),
    ('+377',    'Monaco 🇲🇨 +377'),
    ('+976',    'Mongolia 🇲🇳 +976'),
    ('+382',    'Montenegro 🇲🇪 +382'),
    ('+1 664',  'Montserrat 🇲🇸 +1 664'),
    ('+212',    'Morocco 🇲🇦 +212'),
    ('+258',    'Mozambique 🇲🇿 +258'),
    ('+264',    'Namibia 🇳🇦 +264'),
    ('+674',    'Nauru 🇳🇷 +674'),
    ('+977',    'Nepal 🇳🇵 +977'),
    ('+31',     'Netherlands 🇳🇱 +31'),
    ('+599',    'Netherlands Antilles 🇨🇼🇧🇶 +599'),
    ('+687',    'New Caledonia 🇳🇨 +687'),
    ('+64',     'New Zealand 🇳🇿 +64'),
    ('+505',    'Nicaragua 🇳🇮 +505'),
    ('+227',    'Niger 🇳🇪 +227'),
    ('+234',    'Nigeria 🇳🇬 +234'),
    ('+683',    'Niue 🇳🇺 +683'),
    ('+672',    'Norfolk Island 🇳🇫 +672'),
    ('+850',    'North Korea 🇰🇵 +850'),
    ('+389',    'North Macedonia 🇲🇰 +389'),
    ('+1 670',  'Northern Mariana Islands 🇲🇵 +1 670'),
    ('+47',     'Norway 🇳🇴 +47'),
    ('+968',    'Oman 🇴🇲 +968'),
    ('+92',     'Pakistan 🇵🇰 +92'),
    ('+680',    'Palau 🇵🇼 +680'),
    ('+970',    'Palestine 🇵🇸 +970'),
    ('+507',    'Panama 🇵🇦 +507'),
    ('+675',    'Papua New Guinea 🇵🇬 +675'),
    ('+595',    'Paraguay 🇵🇾 +595'),
    ('+51',     'Peru 🇵🇪 +51'),
    ('+63',     'Philippines 🇵🇭 +63'),
    ('+870',    'Pitcairn Islands 🇵🇳 +870'),
    ('+48',     'Poland 🇵🇱 +48'),
    ('+351',    'Portugal 🇵🇹 +351'),
    ('+1 787',  'Puerto Rico 🇵🇷 +1 787'),
    ('+1 939',  'Puerto Rico 🇵🇷 +1 939'),
    ('+974',    'Qatar 🇶🇦 +974'),
    ('+242',    'Republic of the Congo 🇨🇬 +242'),
    ('+262',    'Reunion Island 🇷🇪 +262'),
    ('+40',     'Romania 🇷🇴 +40'),
    ('+7',      'Russia 🇷🇺 +7'),
    ('+250',    'Rwanda 🇷🇼 +250'),
    ('+590',    'Saint Barthelemy 🇧🇱 +590'),
    ('+290',    'Saint Helena, Ascension and Tristan da Cunha 🇸🇭 +290'),
    ('+1 869',  'Saint Kitts and Nevis 🇰🇳 +1 869'),
    ('+1 758',  'Saint Lucia 🇱🇨 +1 758'),
    ('+590',    'Saint Martin 🇲🇫 +590'),
    ('+508',    'Saint Pierre and Miquelon 🇵🇲 +508'),
    ('+1 784',  'Saint Vincent and the Grenadines 🇻🇨 +1 784'),
    ('+685',    'Samoa 🇼🇸 +685'),
    ('+378',    'San Marino 🇸🇲 +378'),
    ('+239',    'Sao Tome and Principe 🇸🇹 +239'),
    ('+966',    'Saudi Arabia 🇸🇦 +966'),
    ('+221',    'Senegal 🇸🇳 +221'),
    ('+381',    'Serbia 🇷🇸 +381'),
    ('+248',    'Seychelles 🇸🇨 +248'),
    ('+232',    'Sierra Leone 🇸🇱 +232'),
    ('+65',     'Singapore 🇸🇬 +65'),
    ('+1 721',  'Sint Maarten 🇸🇽 +1 721'),
    ('+421',    'Slovakia 🇸🇰 +421'),
    ('+386',    'Slovenia 🇸🇮 +386'),
    ('+677',    'Solomon Islands 🇸🇧 +677'),
    ('+252',    'Somalia 🇸🇴 +252'),
    ('+27',     'South Africa 🇿🇦 +27'),
    ('+82',     'South Korea 🇰🇷 +82'),
    ('+211',    'South Sudan 🇸🇸 +211'),
    ('+34',     'Spain 🇪🇸 +34'),
    ('+94',     'Sri Lanka 🇱🇰 +94'),
    ('+249',    'Sudan 🇸🇩 +249'),
    ('+597',    'Suriname 🇸🇷 +597'),
    ('+47',     'Svalbard 🇸🇯 +47'),
    ('+46',     'Sweden 🇸🇪 +46'),
    ('+41',     'Switzerland 🇨🇭 +41'),
    ('+963',    'Syria 🇸🇾 +963'),
    ('+886',    'Taiwan ROC 🇹🇼 +886'),
    ('+992',    'Tajikistan 🇹🇯 +992'),
    ('+255',    'Tanzania 🇹🇿 +255'),
    ('+66',     'Thailand 🇹🇭 +66'),
    ('+670',    'Timor-Leste (East Timor) 🇹🇱 +670'),
    ('+228',    'Togo 🇹🇬 +228'),
    ('+690',    'Tokelau 🇹🇰 +690'),
    ('+676',    'Tonga 🇹🇴 +676'),
    ('+1 868',  'Trinidad and Tobago 🇹🇹 +1 868'),
    ('+216',    'Tunisia 🇹🇳 +216'),
    ('+90',     'Turkey 🇹🇷 +90'),
    ('+993',    'Turkmenistan 🇹🇲 +993'),
    ('+1 649',  'Turks and Caicos Islands 🇹🇨 +1 649'),
    ('+688',    'Tuvalu 🇹🇻 +688'),
    ('+256',    'Uganda 🇺🇬 +256'),
    ('+380',    'Ukraine 🇺🇦 +380'),
    ('+971',    'United Arab Emirates 🇦🇪 +971'),
    ('+44',     'United Kingdom 🇬🇧 +44'),
    ('+1',      'United States 🇺🇸 +1'),
    ('+598',    'Uruguay 🇺🇾 +598'),
    ('+1 340',  'US Virgin Islands 🇻🇮 +1 340'),
    ('+998',    'Uzbekistan 🇺🇿 +998'),
    ('+678',    'Vanuatu 🇻🇺 +678'),
    ('+58',     'Venezuela 🇻🇪 +58'),
    ('+84',     'Vietnam 🇻🇳 +84'),
    ('+681',    'Wallis and Futuna 🇼🇫 +681'),
    ('+212',    'Western Sahara 🇪🇭 +212'),
    ('+967',    'Yemen 🇾🇪 +967'),
    ('+260',    'Zambia 🇿🇲 +260'),
    ('+263',    'Zimbabwe 🇿🇼 +263'),
    ('Other',   'Other'),
]
DESTINATIONS_GLOBAL = [
    ('AU',	           'Australia 🇦🇺'),
    ('JP',	               'Japan 🇯🇵'),
    ('MY',	            'Malaysia 🇲🇾'),
    ('NZ',	         'New Zealand 🇳🇿'),
    ('SG',	           'Singapore 🇸🇬'),
    ('KR',	         'South Korea 🇰🇷'),
    # ('AF',	         'Afghanistan 🇦🇫'),
    # ('AX',	       'Åland Islands 🇦🇽'),
    # ('AL',	             'Albania 🇦🇱'),
    # ('DZ',	             'Algeria 🇩🇿'),
    # ('AS',	      'American Samoa 🇦🇸'),
    # ('AD',	             'Andorra 🇦🇩'),
    # ('AO',	              'Angola 🇦🇴'),
    # ('AI',	            'Anguilla 🇦🇮'),
    # ('AQ',	          'Antarctica 🇦🇶'),
    # ('AG',	 'Antigua and Barbuda 🇦🇬'),
    # ('AR',	           'Argentina 🇦🇷'),
    # ('AM',	             'Armenia 🇦🇲'),
    # ('AW',	               'Aruba 🇦🇼'),
    # ('AC',	    'Ascension Island 🇦🇨'),
    # ('AT',	             'Austria 🇦🇹'),
    # ('AZ',	          'Azerbaijan 🇦🇿'),
    # ('BS',	             'Bahamas 🇧🇸'),
    # ('BH',	             'Bahrain 🇧🇭'),
    # ('BD',	          'Bangladesh 🇧🇩'),
    # ('BB',	            'Barbados 🇧🇧'),
    # ('BY',	             'Belarus 🇧🇾'),
    # ('BE',	             'Belgium 🇧🇯'),
    # ('BZ',	              'Belize 🇧🇿'),
    # ('BJ',	               'Benin 🇧🇪'),
    # ('BM',	             'Bermuda 🇧🇲'),
    # ('BT',	              'Bhutan 🇧🇹'),
    # ('BO',	             'Bolivia 🇧🇴'),
    # ('BQ',                      'Bonaire, Sint Eustatius and Saba 🇧🇶'),
    # ('BA',	                              'Bosnia and Herzegovina 🇧🇦'),
    # ('BW',	            'Botswana 🇧🇼'),
    # ('BV',	                              'Bouvet Island (Norway) 🇳🇴'),
    # ('BR',	              'Brazil 🇧🇷'),
    # ('IO',	                      'British Indian Ocean Territory 🇮🇴'),
    # ('BN',	              'Brunei 🇧🇳'),
    # ('BG',	            'Bulgaria 🇧🇬'),
    # ('BF',	        'Burkina Faso 🇧🇫'),
    # ('BI',	             'Burundi 🇧🇮'),
    # ('CV',		      'Cape Verde 🇨🇻'),
    # ('KH',	            'Cambodia 🇰🇭'),
    # ('CM',	            'Cameroon 🇨🇲'),
    # ('CA',	              'Canada 🇨🇦'),
    # ('KY',	      'Cayman Islands 🇰🇾'),
    # ('CF',	                            'Central African Republic 🇨🇫'),
    # ('CN',	               'China 🇨🇳'),
    # ('TD',	                'Chad 🇹🇩'),
    # ('CL',	               'Chile 🇨🇱'),
    # ('CX',	    'Christmas Island 🇨🇽'),
    # ('CC',	                            'Cocos (Keeling) Islands 🇨🇨'),
    # ('CO',	            'Colombia 🇨🇴'),
    # ('KM',	             'Comoros 🇰🇲'),
    # ('CD',	                'Congo (Democratic Republic of the ) 🇨🇩'),
    # ('CG',	                           'Congo (Republic of the ) 🇨🇬'),
    # ('CK',	        'Cook Islands 🇨🇰'),
    # ('CR',	          'Costa Rica 🇨🇷'),
    # ('HR',	             'Croatia 🇭🇷'),
    # ('CU',	                'Cuba 🇨🇺'),
    # ('CW',	                     'Curaçao (Netherlands Antilles) 🇨🇼'),
    # ('CY',	              'Cyprus 🇨🇾'),
    # ('CZ',	      'Czech Republic 🇨🇿'),
    # ("CI",	                        "Côte d'Ivoire (Ivory Coast) 🇨🇮"),
    # ('DK',	             'Denmark 🇩🇰'),
    # ('DJ',	            'Djibouti 🇩🇯'),
    # ('DM',	            'Dominica 🇩🇲'),
    # ('DO',	  'Dominican Republic 🇩🇴'),
    # ('EC',	             'Ecuador 🇪🇨'),
    # ('EG',	               'Egypt 🇪🇬'),
    # ('SV',	         'El Salvador 🇸🇻'),
    # ('GQ',	   'Equatorial Guinea 🇬🇶'),
    # ('ER',	             'Eritrea 🇪🇷'),
    # ('EE',	             'Estonia 🇪🇪'),
    # ('SZ',	                               'Eswatini (Swaziland) 🇸🇿'),
    # ('ET',	            'Ethiopia 🇪🇹'),
    # ('FK',	                        'Falkland Islands (Malvinas) 🇫🇰'),
    # ('FO',	       'Faroe Islands 🇫🇴'),
    # ('FJ',	                'Fiji 🇫🇯'),
    # ('FI',	             'Finland 🇫🇮'),
    # ('FR',	              'France 🇫🇷'),
    # ('GF',	       'French Guiana 🇬🇫'),
    # ('PF',	    'French Polynesia 🇵🇫'),
    # ('TF',	                        'French Southern Territories 🇹🇫'),
    # ('GA',	               'Gabon 🇬🇦'),
    # ('GM',	              'Gambia 🇬🇲'),
    # ('GE',	             'Georgia 🇬🇪'),
    # ('DE',	             'Germany 🇩🇪'),
    # ('GH',	               'Ghana 🇬🇭'),
    # ('GI',	           'Gibraltar 🇬🇮'),
    # ('GR',	              'Greece 🇬🇷'),
    # ('GL',	           'Greenland 🇬🇱'),
    # ('GD',	             'Grenada 🇬🇩'),
    # ('GP',	          'Guadeloupe 🇬🇵'),
    # ('GU',	                'Guam 🇬🇺'),
    # ('GT',	           'Guatemala 🇬🇹'),
    # ('GG',	            'Guernsey 🇬🇬'),
    # ('GN',	              'Guinea 🇬🇳'),
    # ('GW',	       'Guinea-Bissau 🇬🇼'),
    # ('GY',	              'Guyana 🇬🇾'),
    # ('HT',	               'Haiti 🇭🇹'),
    # ('HT',                    'Heard Island and McDonald Islands 🇭🇲'),
    # ('VA',	                            'Holy See (Vatican City) 🇻🇦'),
    # ('HN',	            'Honduras 🇭🇳'),
    # ('HU',	             'Hungary 🇭🇺'),
    # ('IS',	             'Iceland 🇮🇸'),
    # ('IN',	               'India 🇮🇳'),
    # ('ID',	           'Indonesia 🇮🇩'),
    # ('IR',	                'Iran 🇮🇷'),
    # ('IQ',	                'Iraq 🇮🇶'),
    # ('IE',	             'Ireland 🇮🇪'),
    # ('IM',	         'Isle of Man 🇮🇲'),
    # ('IL',	              'Israel 🇮🇱'),
    # ('IT',	               'Italy 🇮🇹'),
    # ('JM',	             'Jamaica 🇯🇲'),
    # ('JE',	              'Jersey 🇯🇪'),
    # ('JO',	              'Jordan 🇯🇴'),
    # ('KZ',	          'Kazakhstan 🇰🇿'),
    # ('KE',	               'Kenya 🇰🇪'),
    # ('KI',	            'Kiribati 🇰🇮'),
    # ('KW',	              'Kuwait 🇰🇼'),
    # ('KG',	          'Kyrgyzstan 🇰🇬'),
    # ('LA',	                'Laos 🇱🇦'),
    # ('LV',	              'Latvia 🇱🇻'),
    # ('LB',	             'Lebanon 🇱🇧'),
    # ('LS',	             'Lesotho 🇱🇸'),
    # ('LR',	             'Liberia 🇱🇷'),
    # ('LY',	               'Libya 🇱🇾'),
    # ('LI',	       'Liechtenstein 🇱🇮'),
    # ('LT',	           'Lithuania 🇱🇹'),
    # ('LU',	          'Luxembourg 🇱🇺'),
    # ('MG',	          'Madagascar 🇲🇬'),
    # ('MW',	              'Malawi 🇲🇼'),
    # ('MV',	            'Maldives 🇲🇻'),
    # ('ML',	                'Mali 🇲🇱'),
    # ('MT',	               'Malta 🇲🇹'),
    # ('MH',	    'Marshall Islands 🇲🇭'),
    # ('MQ',	          'Martinique 🇲🇶'),
    # ('MR',	          'Mauritania 🇲🇷'),
    # ('MU',	           'Mauritius 🇲🇺'),
    # ('YT',	             'Mayotte 🇾🇹'),
    # ('MX',	              'Mexico 🇲🇽'),
    # ('FM',	          'Micronesia 🇫🇲'),
    # ('MD',	             'Moldova 🇲🇩'),
    # ('MC',	              'Monaco 🇲🇨'),
    # ('MN',	            'Mongolia 🇲🇳'),
    # ('ME',	          'Montenegro 🇲🇪'),
    # ('MS',	          'Montserrat 🇲🇸'),
    # ('MA',	             'Morocco 🇲🇦'),
    # ('MZ',	          'Mozambique 🇲🇿'),
    # ('MM',	      'Myanmar(Burma) 🇲🇲'),
    # ('NA',	             'Namibia 🇳🇦'),
    # ('NR',	               'Nauru 🇳🇷'),
    # ('NP',	               'Nepal 🇳🇵'),
    # ('NL',	         'Netherlands 🇳🇱'),
    # ('NC',	       'New Caledonia 🇳🇨'),
    # ('NI',	           'Nicaragua 🇳🇮'),
    # ('NE',	               'Niger 🇳🇪'),
    # ('NG',	             'Nigeria 🇳🇬'),
    # ('NU',	                'Niue 🇳🇺'),
    # ('NF',	      'Norfolk Island 🇳🇫'),
    # ('MP',	                            'Northern Mariana Islands 🇲🇵'),
    # ('KP',	         'North Korea 🇰🇵'),
    # ('NO',	              'Norway 🇳🇴'),
    # ('OM',	                'Oman 🇴🇲'),
    # ('PK',	            'Pakistan 🇵🇰'),
    # ('PW',	               'Palau 🇵🇼'),
    # ('PS',	           'Palestine 🇵🇸'),
    # ('PA',	              'Panama 🇵🇦'),
    # ('PG',	    'Papua New Guinea 🇵🇬'),
    # ('PY',	            'Paraguay 🇵🇾'),
    # ('PE',	                'Peru 🇵🇪'),
    # ('PH',	         'Philippines 🇵🇭'),
    # ('PN',	    'Pitcairn Islands 🇵🇳'),
    # ('PL',	              'Poland 🇵🇱'),
    # ('PT',	            'Portugal 🇵🇹'),
    # ('PR',	         'Puerto Rico 🇵🇷'),
    # ('QA',	               'Qatar 🇶🇦'),
    # ('MK',	     'North Macedonia 🇲🇰'),
    # ('RO',	             'Romania 🇷🇴'),
    # ('RU',	              'Russia 🇷🇺'),
    # ('RW',	              'Rwanda 🇷🇼'),
    # ('RE',	      'Reunion Island 🇷🇪'),
    # ('BL',	    'Saint Barthelemy 🇧🇱'),
    # ('SH',	        'Saint Helena, Ascension and Tristan da Cunha 🇸🇭'),
    # ('KN', 'Saint Kitts and Nevis 🇰🇳'),
    # ('LC',	         'Saint Lucia 🇱🇨'),
    # ('MF',	        'Saint Martin 🇲🇫'),
    # ('PM',	                           'Saint Pierre and Miquelon 🇵🇲'),
    # ('VC',	                    'Saint Vincent and the Grenadines 🇻🇨'),
    # ('WS',	               'Samoa 🇼🇸'),
    # ('SM',	          'San Marino 🇸🇲'),
    # ('ST', 'Sao Tome and Principe 🇸🇹'),
    # ('SA',	        'Saudi Arabia 🇸🇦'),
    # ('SN',	             'Senegal 🇸🇳'),
    # ('RS',	              'Serbia 🇷🇸'),
    # ('SC',	          'Seychelles 🇸🇨'),
    # ('SL',	        'Sierra Leone 🇸🇱'),
    # ('SX',	        'Sint Maarten 🇸🇽'),
    # ('SK',	            'Slovakia 🇸🇰'),
    # ('SI',	            'Slovenia 🇸🇮'),
    # ('SB',	     'Solomon Islands 🇸🇧'),
    # ('SO',	             'Somalia 🇸🇴'),
    # ('ZA',	        'South Africa 🇿🇦'),
    # ('GS',	        'South Georgia and the South Sandwich Islands 🇬🇸'),
    # ('SS',	         'South Sudan 🇸🇸'),
    # ('ES',	               'Spain 🇪🇸'),
    # ('LK',	           'Sri Lanka 🇱🇰'),
    # ('SD',	               'Sudan 🇸🇩'),
    # ('SR',	            'Suriname 🇸🇷'),
    # ('SJ',	             'Svalbard and Jan Mayen Islands (Norway) 🇸🇯'),
    # ('SE',	              'Sweden 🇸🇪'),
    # ('CH',	         'Switzerland 🇨🇭'),
    # ('SY',	               'Syria 🇸🇾'),
    # ('TJ',	          'Tajikistan 🇹🇯'),
    # ('TZ',	            'Tanzania 🇹🇿'),
    # ('TH',	            'Thailand 🇹🇭'),
    # ('TL',	                            'Timor-Leste (East Timor) 🇹🇱'),
    # ('TG',	                'Togo 🇹🇬'),
    # ('TK',	             'Tokelau 🇹🇰'),
    # ('TO',	               'Tonga 🇹🇴'),
    # ('TT',	 'Trinidad and Tobago 🇹🇹'),
    # ('TN',	             'Tunisia 🇹🇳'),
    # ('TR',	              'Turkey 🇹🇷'),
    # ('TM',	        'Turkmenistan 🇹🇲'),
    # ('TC',	                            'Turks and Caicos Islands 🇹🇨'),
    # ('TV',	              'Tuvalu 🇹🇻'),
    # ('UG',	              'Uganda 🇺🇬'),
    # ('UA',	             'Ukraine 🇺🇦'),
    # ('AE',	                                'United Arab Emirates 🇦🇪'),
    # ('GB',	      'United Kingdom 🇬🇧'),
    # ('UM',	        'United States Minor Outlying Islands (USMOI) 🇺🇸'),
    # ('US',	       'United States 🇺🇸'),
    # ('UY',	             'Uruguay 🇺🇾'),
    # ('UZ',	          'Uzbekistan 🇺🇿'),
    # ('VU',	             'Vanuatu 🇻🇺'),
    # ('VE',	           'Venezuela 🇻🇪'),
    # ('VN',	             'Vietnam 🇻🇳'),
    # ('VG',	                            'Virgin Islands (British) 🇻🇬'),
    # ('VI',	 'Virgin Islands (US) 🇻🇮'),
    # ('WF',	   'Wallis and Futuna 🇼🇫'),
    # ('EH',	      'Western Sahara 🇪🇭'),
    # ('YE',	               'Yemen 🇦🇪'),
    # ('ZM',	              'Zambia 🇿🇲'),
    # ('ZW',	            'Zimbabwe 🇿🇼'),
]
DESTINATIONS_GREATER_CHINA = [
    ('HK',                   'Hong Kong 🇭🇰'),
    ('MO',	                 'Macao SAR 🇲🇴'),
    ('TW',	                'Taiwan ROC 🇹🇼'),
]
DESTINATIONS_MAINLAND_CHINA = [
    ('Beijing',             '北京市|Běijīng'),
    ('Chongqing',           '重慶市|Chóngqìng'),
    ('Shanghai',            '上海市|Shànghǎi'),
    ('Tianjin',             '天津市|Tiānjīn'),
    ('Anhui',               '安徽省|Ānhuī'),
    ('Fujian',              '福建省|Fújiàn'),
    ('Gansu',               '甘肅省|Gānsù'),
    ('Guandong',            '廣東省|Guǎngdōng'),
    ('Guizhou',             '貴州省|Guìzhōu'),
    ('Hainan',              '海南省|Hǎinán'),
    ('Hebei',               '河北省|Héběi'),
    ('Heilongjiang',        '黑龍江省|Hēilóngjiāng'),
    ('Henan',               '河南省|Hénán'),
    ('Hubei',               '湖北省|Húběi'),
    ('Hunan',               '湖南省|Húnán'),
    ('Jiangsu',             '江蘇省|Jiāngsū'),
    ('Jiangxi',             '江西省|Jiāngxī'),
    ('Jilin',               '吉林省|Jílín'),
    ('Liaoning',            '遼寧省|Liáoníng'),
    ('Qinghai',             '青海省|Qīnghǎi'),
    ('Shan(3)xi',           '陝西省|Shǎnxī'),
    ('Shandong',            '山東省|Shāndōng'),
    ('Shan(1)xi',           '山西省|Shānxī'),
    ('Sichuan',             '四川省|Sìchuān'),
    ('Yunnan',              '雲南省|Yúnnán'),
    ('Zhejiang',            '浙江省|Zhèjiāng'),
    ('Guangxi',             '廣西壯族自治區|Guǎngxī'),
    ('Neimenggu',           '內蒙古自治區|Nèiměnggǔ'),
    ('Ningxia',             '寧夏回族自治區|Níngxià'),
    ('Xinjiang',            '新疆維吾爾自治區|Xīnjiāng'),
    ('Xizang',              '西藏自治區|Xīzàng'),
]
DESTINATIONS_FOR_INPUT = [
    ('AU',	           'Australia 🇦🇺'),
    ('CN',	               'China 🇨🇳'),
    ('HK',             'Hong Kong 🇭🇰'),
    ('JP',	               'Japan 🇯🇵'),
    ('MO',	           'Macao SAR 🇲🇴'),
    ('MY',	            'Malaysia 🇲🇾'),
    ('NZ',	         'New Zealand 🇳🇿'),
    ('SG',	           'Singapore 🇸🇬'),
    ('KR',	         'South Korea 🇰🇷'),
    ('TW',	          'Taiwan ROC 🇹🇼'),
    # ('',	'Country/Region｜國家/地區 🌏'),
    # ('AF',	         'Afghanistan 🇦🇫'),
    # ('AX',	       'Åland Islands 🇦🇽'),
    # ('AL',	             'Albania 🇦🇱'),
    # ('DZ',	             'Algeria 🇩🇿'),
    # ('AS',	      'American Samoa 🇦🇸'),
    # ('AD',	             'Andorra 🇦🇩'),
    # ('AO',	              'Angola 🇦🇴'),
    # ('AI',	            'Anguilla 🇦🇮'),
    # ('AQ',	          'Antarctica 🇦🇶'),
    # ('AG',	 'Antigua and Barbuda 🇦🇬'),
    # ('AR',	           'Argentina 🇦🇷'),
    # ('AM',	             'Armenia 🇦🇲'),
    # ('AW',	               'Aruba 🇦🇼'),
    # ('AC',	    'Ascension Island 🇦🇨'),
    # ('AT',	             'Austria 🇦🇹'),
    # ('AZ',	          'Azerbaijan 🇦🇿'),
    # ('BS',	             'Bahamas 🇧🇸'),
    # ('BH',	             'Bahrain 🇧🇭'),
    # ('BD',	          'Bangladesh 🇧🇩'),
    # ('BB',	            'Barbados 🇧🇧'),
    # ('BY',	             'Belarus 🇧🇾'),
    # ('BE',	             'Belgium 🇧🇯'),
    # ('BZ',	              'Belize 🇧🇿'),
    # ('BJ',	               'Benin 🇧🇪'),
    # ('BM',	             'Bermuda 🇧🇲'),
    # ('BT',	              'Bhutan 🇧🇹'),
    # ('BO',	             'Bolivia 🇧🇴'),
    # ('BQ',                      'Bonaire, Sint Eustatius and Saba 🇧🇶'),
    # ('BA',	                              'Bosnia and Herzegovina 🇧🇦'),
    # ('BW',	            'Botswana 🇧🇼'),
    # ('BV',	                              'Bouvet Island (Norway) 🇳🇴'),
    # ('BR',	              'Brazil 🇧🇷'),
    # ('IO',	                      'British Indian Ocean Territory 🇮🇴'),
    # ('BN',	              'Brunei 🇧🇳'),
    # ('BG',	            'Bulgaria 🇧🇬'),
    # ('BF',	        'Burkina Faso 🇧🇫'),
    # ('BI',	             'Burundi 🇧🇮'),
    # ('CV',		      'Cape Verde 🇨🇻'),
    # ('KH',	            'Cambodia 🇰🇭'),
    # ('CM',	            'Cameroon 🇨🇲'),
    # ('CA',	              'Canada 🇨🇦'),
    # ('KY',	      'Cayman Islands 🇰🇾'),
    # ('CF',	                            'Central African Republic 🇨🇫'),
    # ('TD',	                'Chad 🇹🇩'),
    # ('CL',	               'Chile 🇨🇱'),
    # ('CX',	    'Christmas Island 🇨🇽'),
    # ('CC',	                            'Cocos (Keeling) Islands 🇨🇨'),
    # ('CO',	            'Colombia 🇨🇴'),
    # ('KM',	             'Comoros 🇰🇲'),
    # ('CD',	                'Congo (Democratic Republic of the ) 🇨🇩'),
    # ('CG',	                           'Congo (Republic of the ) 🇨🇬'),
    # ('CK',	        'Cook Islands 🇨🇰'),
    # ('CR',	          'Costa Rica 🇨🇷'),
    # ('HR',	             'Croatia 🇭🇷'),
    # ('CU',	                'Cuba 🇨🇺'),
    # ('CW',	                     'Curaçao (Netherlands Antilles) 🇨🇼'),
    # ('CY',	              'Cyprus 🇨🇾'),
    # ('CZ',	      'Czech Republic 🇨🇿'),
    # ("CI",	                        "Côte d'Ivoire (Ivory Coast) 🇨🇮"),
    # ('DK',	             'Denmark 🇩🇰'),
    # ('DJ',	            'Djibouti 🇩🇯'),
    # ('DM',	            'Dominica 🇩🇲'),
    # ('DO',	  'Dominican Republic 🇩🇴'),
    # ('EC',	             'Ecuador 🇪🇨'),
    # ('EG',	               'Egypt 🇪🇬'),
    # ('SV',	         'El Salvador 🇸🇻'),
    # ('GQ',	   'Equatorial Guinea 🇬🇶'),
    # ('ER',	             'Eritrea 🇪🇷'),
    # ('EE',	             'Estonia 🇪🇪'),
    # ('SZ',	                               'Eswatini (Swaziland) 🇸🇿'),
    # ('ET',	            'Ethiopia 🇪🇹'),
    # ('FK',	                        'Falkland Islands (Malvinas) 🇫🇰'),
    # ('FO',	       'Faroe Islands 🇫🇴'),
    # ('FJ',	                'Fiji 🇫🇯'),
    # ('FI',	             'Finland 🇫🇮'),
    # ('FR',	              'France 🇫🇷'),
    # ('GF',	       'French Guiana 🇬🇫'),
    # ('PF',	    'French Polynesia 🇵🇫'),
    # ('TF',	                        'French Southern Territories 🇹🇫'),
    # ('GA',	               'Gabon 🇬🇦'),
    # ('GM',	              'Gambia 🇬🇲'),
    # ('GE',	             'Georgia 🇬🇪'),
    # ('DE',	             'Germany 🇩🇪'),
    # ('GH',	               'Ghana 🇬🇭'),
    # ('GI',	           'Gibraltar 🇬🇮'),
    # ('GR',	              'Greece 🇬🇷'),
    # ('GL',	           'Greenland 🇬🇱'),
    # ('GD',	             'Grenada 🇬🇩'),
    # ('GP',	          'Guadeloupe 🇬🇵'),
    # ('GU',	                'Guam 🇬🇺'),
    # ('GT',	           'Guatemala 🇬🇹'),
    # ('GG',	            'Guernsey 🇬🇬'),
    # ('GN',	              'Guinea 🇬🇳'),
    # ('GW',	       'Guinea-Bissau 🇬🇼'),
    # ('GY',	              'Guyana 🇬🇾'),
    # ('HT',	               'Haiti 🇭🇹'),
    # ('HT',                    'Heard Island and McDonald Islands 🇭🇲'),
    # ('VA',	                            'Holy See (Vatican City) 🇻🇦'),
    # ('HN',	            'Honduras 🇭🇳'),
    # ('HU',	             'Hungary 🇭🇺'),
    # ('IS',	             'Iceland 🇮🇸'),
    # ('IN',	               'India 🇮🇳'),
    # ('ID',	           'Indonesia 🇮🇩'),
    # ('IR',	                'Iran 🇮🇷'),
    # ('IQ',	                'Iraq 🇮🇶'),
    # ('IE',	             'Ireland 🇮🇪'),
    # ('IM',	         'Isle of Man 🇮🇲'),
    # ('IL',	              'Israel 🇮🇱'),
    # ('IT',	               'Italy 🇮🇹'),
    # ('JM',	             'Jamaica 🇯🇲'),
    # ('JE',	              'Jersey 🇯🇪'),
    # ('JO',	              'Jordan 🇯🇴'),
    # ('KZ',	          'Kazakhstan 🇰🇿'),
    # ('KE',	               'Kenya 🇰🇪'),
    # ('KI',	            'Kiribati 🇰🇮'),
    # ('KW',	              'Kuwait 🇰🇼'),
    # ('KG',	          'Kyrgyzstan 🇰🇬'),
    # ('LA',	                'Laos 🇱🇦'),
    # ('LV',	              'Latvia 🇱🇻'),
    # ('LB',	             'Lebanon 🇱🇧'),
    # ('LS',	             'Lesotho 🇱🇸'),
    # ('LR',	             'Liberia 🇱🇷'),
    # ('LY',	               'Libya 🇱🇾'),
    # ('LI',	       'Liechtenstein 🇱🇮'),
    # ('LT',	           'Lithuania 🇱🇹'),
    # ('LU',	          'Luxembourg 🇱🇺'),
    # ('MG',	          'Madagascar 🇲🇬'),
    # ('MW',	              'Malawi 🇲🇼'),
    # ('MV',	            'Maldives 🇲🇻'),
    # ('ML',	                'Mali 🇲🇱'),
    # ('MT',	               'Malta 🇲🇹'),
    # ('MH',	    'Marshall Islands 🇲🇭'),
    # ('MQ',	          'Martinique 🇲🇶'),
    # ('MR',	          'Mauritania 🇲🇷'),
    # ('MU',	           'Mauritius 🇲🇺'),
    # ('YT',	             'Mayotte 🇾🇹'),
    # ('MX',	              'Mexico 🇲🇽'),
    # ('FM',	          'Micronesia 🇫🇲'),
    # ('MD',	             'Moldova 🇲🇩'),
    # ('MC',	              'Monaco 🇲🇨'),
    # ('MN',	            'Mongolia 🇲🇳'),
    # ('ME',	          'Montenegro 🇲🇪'),
    # ('MS',	          'Montserrat 🇲🇸'),
    # ('MA',	             'Morocco 🇲🇦'),
    # ('MZ',	          'Mozambique 🇲🇿'),
    # ('MM',	      'Myanmar(Burma) 🇲🇲'),
    # ('NA',	             'Namibia 🇳🇦'),
    # ('NR',	               'Nauru 🇳🇷'),
    # ('NP',	               'Nepal 🇳🇵'),
    # ('NL',	         'Netherlands 🇳🇱'),
    # ('NC',	       'New Caledonia 🇳🇨'),
    # ('NI',	           'Nicaragua 🇳🇮'),
    # ('NE',	               'Niger 🇳🇪'),
    # ('NG',	             'Nigeria 🇳🇬'),
    # ('NU',	                'Niue 🇳🇺'),
    # ('NF',	      'Norfolk Island 🇳🇫'),
    # ('MP',	                            'Northern Mariana Islands 🇲🇵'),
    # ('KP',	         'North Korea 🇰🇵'),
    # ('NO',	              'Norway 🇳🇴'),
    # ('OM',	                'Oman 🇴🇲'),
    # ('PK',	            'Pakistan 🇵🇰'),
    # ('PW',	               'Palau 🇵🇼'),
    # ('PS',	           'Palestine 🇵🇸'),
    # ('PA',	              'Panama 🇵🇦'),
    # ('PG',	    'Papua New Guinea 🇵🇬'),
    # ('PY',	            'Paraguay 🇵🇾'),
    # ('PE',	                'Peru 🇵🇪'),
    # ('PH',	         'Philippines 🇵🇭'),
    # ('PN',	    'Pitcairn Islands 🇵🇳'),
    # ('PL',	              'Poland 🇵🇱'),
    # ('PT',	            'Portugal 🇵🇹'),
    # ('PR',	         'Puerto Rico 🇵🇷'),
    # ('QA',	               'Qatar 🇶🇦'),
    # ('MK',	     'North Macedonia 🇲🇰'),
    # ('RO',	             'Romania 🇷🇴'),
    # ('RU',	              'Russia 🇷🇺'),
    # ('RW',	              'Rwanda 🇷🇼'),
    # ('RE',	      'Reunion Island 🇷🇪'),
    # ('BL',	    'Saint Barthelemy 🇧🇱'),
    # ('SH',	        'Saint Helena, Ascension and Tristan da Cunha 🇸🇭'),
    # ('KN', 'Saint Kitts and Nevis 🇰🇳'),
    # ('LC',	         'Saint Lucia 🇱🇨'),
    # ('MF',	        'Saint Martin 🇲🇫'),
    # ('PM',	                           'Saint Pierre and Miquelon 🇵🇲'),
    # ('VC',	                    'Saint Vincent and the Grenadines 🇻🇨'),
    # ('WS',	               'Samoa 🇼🇸'),
    # ('SM',	          'San Marino 🇸🇲'),
    # ('ST', 'Sao Tome and Principe 🇸🇹'),
    # ('SA',	        'Saudi Arabia 🇸🇦'),
    # ('SN',	             'Senegal 🇸🇳'),
    # ('RS',	              'Serbia 🇷🇸'),
    # ('SC',	          'Seychelles 🇸🇨'),
    # ('SL',	        'Sierra Leone 🇸🇱'),
    # ('SX',	        'Sint Maarten 🇸🇽'),
    # ('SK',	            'Slovakia 🇸🇰'),
    # ('SI',	            'Slovenia 🇸🇮'),
    # ('SB',	     'Solomon Islands 🇸🇧'),
    # ('SO',	             'Somalia 🇸🇴'),
    # ('ZA',	        'South Africa 🇿🇦'),
    # ('GS',	        'South Georgia and the South Sandwich Islands 🇬🇸'),
    # ('SS',	         'South Sudan 🇸🇸'),
    # ('ES',	               'Spain 🇪🇸'),
    # ('LK',	           'Sri Lanka 🇱🇰'),
    # ('SD',	               'Sudan 🇸🇩'),
    # ('SR',	            'Suriname 🇸🇷'),
    # ('SJ',	             'Svalbard and Jan Mayen Islands (Norway) 🇸🇯'),
    # ('SE',	              'Sweden 🇸🇪'),
    # ('CH',	         'Switzerland 🇨🇭'),
    # ('SY',	               'Syria 🇸🇾'),
    # ('TJ',	          'Tajikistan 🇹🇯'),
    # ('TZ',	            'Tanzania 🇹🇿'),
    # ('TH',	            'Thailand 🇹🇭'),
    # ('TL',	                            'Timor-Leste (East Timor) 🇹🇱'),
    # ('TG',	                'Togo 🇹🇬'),
    # ('TK',	             'Tokelau 🇹🇰'),
    # ('TO',	               'Tonga 🇹🇴'),
    # ('TT',	 'Trinidad and Tobago 🇹🇹'),
    # ('TN',	             'Tunisia 🇹🇳'),
    # ('TR',	              'Turkey 🇹🇷'),
    # ('TM',	        'Turkmenistan 🇹🇲'),
    # ('TC',	                            'Turks and Caicos Islands 🇹🇨'),
    # ('TV',	              'Tuvalu 🇹🇻'),
    # ('UG',	              'Uganda 🇺🇬'),
    # ('UA',	             'Ukraine 🇺🇦'),
    # ('AE',	                                'United Arab Emirates 🇦🇪'),
    # ('GB',	      'United Kingdom 🇬🇧'),
    # ('UM',	        'United States Minor Outlying Islands (USMOI) 🇺🇸'),
    # ('US',	       'United States 🇺🇸'),
    # ('UY',	             'Uruguay 🇺🇾'),
    # ('UZ',	          'Uzbekistan 🇺🇿'),
    # ('VU',	             'Vanuatu 🇻🇺'),
    # ('VE',	           'Venezuela 🇻🇪'),
    # ('VN',	             'Vietnam 🇻🇳'),
    # ('VG',	                            'Virgin Islands (British) 🇻🇬'),
    # ('VI',	 'Virgin Islands (US) 🇻🇮'),
    # ('WF',	   'Wallis and Futuna 🇼🇫'),
    # ('EH',	      'Western Sahara 🇪🇭'),
    # ('YE',	               'Yemen 🇦🇪'),
    # ('ZM',	              'Zambia 🇿🇲'),
    # ('ZW',	            'Zimbabwe 🇿🇼'),
]
GENDER = [
        ('DEFAULT',     '♂♀⚥'),
        ('MALE',        '男性 | Male'),
        ('FEMALE',      '女性 | Female'),
        ('SECRET',      '秘密 | Secret'),
    ]
BLOOD = [
        ('DEFAULT', '🩸'),
        ('TYPE_A', 'A'),
        ('TYPE_B', 'B'),
        ('TYPE_AB', 'AB'),
        ('TYPE_O', 'O'),
        ('TYPE_OTHER', '其他 | Other'),
    ]
COLOR = [
    ('DEFAULT',     '🎨'),
    ('RED',         '紅色 | Red'),
    ('PINK',        '粉色 | Pink'),
    ('ORANGE',      '橙色 | Orange'),
    ('YELLOW',      '黃色 | Yellow'),
    ('PURPLE',      '紫色 | Purple'),
    ('GREEN',       '綠色 | Green'),
    ('BLUE',        '藍色 | Blue'),
    ('BROWN',       '棕色 | Brown'),
    ('WHITE',       '白色 | White'),
    ('GRAY',        '灰色 | Gray'),
    ('BLACK',       '黑色 | Black'),
    ('OTHER',       '其他 | Other'),
]
LABEL = [
    ('',            '標籤🏷️🪹 | Label'),
    ('home',        '家🏠｜Home'),
    ('work',        '工作🏢｜Work'),
    ('school',      '學校🏫｜School'),
    ('other',       '其他🛸｜Other'),
]
CURRENCIES = [
    "HKD",
    "TWD",
    "CNY",
    "JPY",
    "SGD",
    "MYR",
    "AUD",
    "NZD",
    "USD",
    # "MOP",
    # "CAD",
    # "EUR",
    # "GBP",
    # "KRW",
    # "INR",
    # "MXN",
    # "RUB",
    # "BRL",
    # "ZAR",
    # "TRY",
    # "SEK",
    # "NOK",
    # "DKK",
    # "PLN",
    # "THB",
    # "IDR",
    # "PHP",
    # "CLP",
    # "COP",
    # "RON",
    # "MAD",
    # "AED",
    # "SAR",
    # "LKR",
    # "NPR",
    # "PKR",
    # "BDT",
    # "VND",
]

INTEGER_CURRENCIES = [
    "JPY",
    "KRW",
    "TWD",
    "VND",
    "CLP"
]

CURRENCY_LOCALE = {
    "HKD": "en-HK",
    "MOP": "pt-MO",
    "TWD": "zh-TW",
    "SGD": "en-SG",
    "USD": "en-US",
    "CAD": "en-CA",
    "JPY": "ja-JP",
    "AUD": "en-AU",
    "EUR": "en-IE",
    "GBP": "en-GB",
    "KRW": "ko-KR",
    "INR": "en-IN",
    "MXN": "es-MX",
    "RUB": "ru-RU",
    "BRL": "pt-BR",
    "ZAR": "af-ZA",
    "TRY": "tr-TR",
    "SEK": "sv-SE",
    "NOK": "nb-NO",
    "DKK": "da-DK",
    "PLN": "pl-PL",
    "THB": "th-TH",
    "IDR": "id-ID",
    "PHP": "en-PH",
    "MYR": "ms-MY",
    "CLP": "es-CL",
    "COP": "es-CO",
    "RON": "ro-RO",
    "MAD": "ar-MA",
    "AED": "ar-AE",
    "SAR": "ar-SA",
    "LKR": "si-LK",
    "NPR": "ne-NP",
    "PKR": "en-PK ",
    "BDT": "bn-BD",
    "VND": "vi-VN",
}

COUNTRY_CODE = {
    "HKD": "HK",
    "MOP": "MO",
    "TWD": "TW",
    "SGD": "SG",
    "USD": "US",
    "CAD": "CA",
    "JPY": "JP",
    "AUD": "AU",
    "EUR": "EU",
    "GBP": "GB",
    "KRW": "KR",
    "INR": "IN",
    "MXN": "MX",
    "RUB": "RU",
    "BRL": "BR",
    "ZAR": "ZA",
    "TRY": "TR",
    "SEK": "SE",
    "NOK": "NO",
    "DKK": "DK",
    "PLN": "PL",
    "THB": "TH",
    "IDR": "ID",
    "PHP": "PH",
    "MYR": "MY",
    "CLP": "CL",
    "COP": "CO",
    "RON": "RO",
    "MAD": "MA",
    "AED": "AE",
    "SAR": "SA",
    "LKR": "LK",
    "NPR": "NP",
    "PKR": "PK",
    "BDT": "BD",
    "VND": "VN",
}

CURRENCY_SYMBOL = {
    "CNY": "¥",
    "HKD": "HK$",
    "MOP": "MOP$",
    "TWD": "NT$",
    "SGD": "S$",
    "USD": "$",
    "CAD": "C$",
    "JPY": "¥", 
    "AUD": "A$",
    "EUR": "€",
    "GBP": "£",
    "KRW": "₩",
    "INR": "₹",
    "MXN": "Mex$",
    "RUB": "₽",
    "BRL": "R$",
    "ZAR": "R",
    "TRY": "₺",
    "SEK": "kr",
    "NOK": "kr",
    "DKK": "kr",
    "PLN": "zł",
    "THB": "฿",
    "IDR": "Rp",
    "PHP": "₱",
    "MYR": "RM",
    "CLP": "$",
    "COP": "$",
    "RON": "lei",
    "MAD": "د.م.",
    "AED": "د.إ",
    "SAR": "ر.س",
    "LKR": "₨",
    "NPR": "₨",
    "PKR": "₨",
    "BDT": "৳",
    "VND": "₫",
}

INTERNAL_CURRENCY_ADJUSTMENT = 1.05

DEFAULT_EXCHANGE_RATE_VS_CNY = {
    "HKD": 1.1196 * INTERNAL_CURRENCY_ADJUSTMENT,
    "MOP": 1.1551 * INTERNAL_CURRENCY_ADJUSTMENT,
    "TWD": 4.7281 * INTERNAL_CURRENCY_ADJUSTMENT,
    "SGD": 0.1852 * INTERNAL_CURRENCY_ADJUSTMENT,
    "USD": 0.1437 * INTERNAL_CURRENCY_ADJUSTMENT,
    "CAD": 0.2036 * INTERNAL_CURRENCY_ADJUSTMENT,
    "JPY": 22.49 * INTERNAL_CURRENCY_ADJUSTMENT,
    "AUD": 0.2140 * INTERNAL_CURRENCY_ADJUSTMENT,
    "EUR": 0.1283 * INTERNAL_CURRENCY_ADJUSTMENT,
    "GBP": 0.1064 * INTERNAL_CURRENCY_ADJUSTMENT,
    "KRW": 173.08 * INTERNAL_CURRENCY_ADJUSTMENT,
    "INR": 10.63 * INTERNAL_CURRENCY_ADJUSTMENT,
    "MXN": 2.56 * INTERNAL_CURRENCY_ADJUSTMENT,
    "RUB": 11.16 * INTERNAL_CURRENCY_ADJUSTMENT,
    "BRL": 0.7711 * INTERNAL_CURRENCY_ADJUSTMENT,
    "ZAR": 2.36 * INTERNAL_CURRENCY_ADJUSTMENT,
    "TRY": 6.20 * INTERNAL_CURRENCY_ADJUSTMENT,
    "SEK": 1.33 * INTERNAL_CURRENCY_ADJUSTMENT,
    "NOK": 1.45 * INTERNAL_CURRENCY_ADJUSTMENT,
    "DKK": 0.92 * INTERNAL_CURRENCY_ADJUSTMENT,
    "PLN": 0.52 * INTERNAL_CURRENCY_ADJUSTMENT,
    "THB": 4.51 * INTERNAL_CURRENCY_ADJUSTMENT,
    "IDR": 2420.75 * INTERNAL_CURRENCY_ADJUSTMENT,
    "PHP": 8.52 * INTERNAL_CURRENCY_ADJUSTMENT,
    "MYR": 0.58 * INTERNAL_CURRENCY_ADJUSTMENT,
    "CLP": 126.80 * INTERNAL_CURRENCY_ADJUSTMENT,
    "COP": 532.99 * INTERNAL_CURRENCY_ADJUSTMENT,
    "RON": 0.63 * INTERNAL_CURRENCY_ADJUSTMENT,
    "MAD": 1.32 * INTERNAL_CURRENCY_ADJUSTMENT,
    "AED": 0.53 * INTERNAL_CURRENCY_ADJUSTMENT,
    "SAR": 0.54 * INTERNAL_CURRENCY_ADJUSTMENT,
    "QAR": 0.53 * INTERNAL_CURRENCY_ADJUSTMENT,
    "LKR": 44.31 * INTERNAL_CURRENCY_ADJUSTMENT,
    "NPR": 20.42 * INTERNAL_CURRENCY_ADJUSTMENT,
    "PKR": 40.25 * INTERNAL_CURRENCY_ADJUSTMENT,
    "BDT": 17.56 * INTERNAL_CURRENCY_ADJUSTMENT,
    "VND": 3538.80 * INTERNAL_CURRENCY_ADJUSTMENT,
}

SOLAR = {
    "小寒": "Minor Cold",
    "大寒": "Major Cold",
    "立春": "Beginning of Spring",
    "雨水": "Rain Water",
    "惊蛰": "Awakening of Insects",
    "春分": "Spring Equinox",
    "清明": "Pure Brightness",
    "谷雨": "Grain Rain",
    "立夏": "Beginning of Summer",
    "小满": "Grain Buds",
    "芒种": "Grain in Ear",
    "夏至": "Summer Solstice",
    "小暑": "Minor Heat",
    "大暑": "Major Heat",
    "立秋": "Beginning of Autumn",
    "处暑": "End of Heat",
    "白露": "White Dew",
    "秋分": "Autumnal Equinox",
    "寒露": "Cold Dew",
    "霜降": "Frost's Descent",
    "立冬": "Beginning of Winter",
    "小雪": "Minor Snow",
    "大雪": "Major Snow",
    "冬至": "Winter Solstice",
}

CUSTOMER_GROUP = [
    ('DEFAULT', '👤'),
    ('VIP', '💎'),
    ('VVIP', '👑'),
]
