# Generated by Django 5.2.7 on 2025-11-10 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariation",
            name="images",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/products/variations"
            ),
        ),
        migrations.AlterField(
            model_name="productvariation",
            name="color",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="store.color",
            ),
        ),
        migrations.AlterField(
            model_name="productvariation",
            name="size",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="store.size"
            ),
        ),
        migrations.AlterField(
            model_name="productvariation",
            name="type",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="store.type"
            ),
        ),
    ]
