# Generated by Django 5.2.7 on 2025-11-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_productvariation_images_alter_productvariation_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariation",
            name="original_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
