# Generated by Django 5.2.7 on 2025-11-10 12:57

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_productvariation_original_price"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="product",
            managers=[
                ("products", django.db.models.manager.Manager()),
            ],
        ),
    ]
