# Generated by Django 5.2.7 on 2025-11-12 02:34

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_product_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="details",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
