# Generated by Django 5.2.7 on 2025-11-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_product_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariation",
            name="images",
            field=models.ImageField(upload_to="images/products/variations"),
        ),
    ]
