# Generated by Django 5.2.7 on 2025-11-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_alter_productvariation_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariation",
            name="images",
            field=models.ImageField(
                default="images/products/variations/pattern1.png",
                upload_to="images/products/variations",
            ),
        ),
    ]
