# Generated by Django 5.2.7 on 2025-11-18 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_alter_productvariation_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="origin",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DEFAULT", "地球|EARTH"),
                    ("CHINA", "中國|CHINA"),
                    ("AUSTRALIA", "澳大利亞|AUSTRALIA"),
                    ("TYPE_OTHER", "其他|Other"),
                ],
                default="DEFAULT",
                max_length=50,
            ),
        ),
    ]
