# Generated by Django 5.2.7 on 2025-12-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_productgallery_productvariationgallery"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productgallery",
            options={
                "verbose_name": "ProductGallery",
                "verbose_name_plural": "Product Gallery",
            },
        ),
        migrations.AlterModelOptions(
            name="productvariationgallery",
            options={
                "verbose_name": "ProductVariationGallery",
                "verbose_name_plural": "ProductVariation Gallery",
            },
        ),
        migrations.AddField(
            model_name="productgallery",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="productvariationgallery",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
