# Generated by Django 5.2.7 on 2025-12-12 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_productgallery_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='with_shipping',
        ),
    ]
