# Generated by Django 5.2.7 on 2025-12-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_product_with_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='single_pack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='weight',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='with_shipping',
            field=models.BooleanField(default=False),
        ),
    ]
