# Generated by Django 6.0.1 on 2026-03-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0012_productvariation_single_pack_productvariation_weight_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="blood",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DEFAULT", "未指定|UNSPECIFIED"),
                    ("A", "A型|TYPE_A"),
                    ("B", "B型|TYPE_B"),
                    ("AB", "AB型|TYPE_AB"),
                    ("O", "O型|TYPE_O"),
                    ("OTHER", "其他|OTHER"),
                ],
                default="DEFAULT",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DEFAULT", "未指定|UNSPECIFIED"),
                    ("RED", "Red｜紅色"),
                    ("PINK", "Pink｜粉紅色"),
                    ("ORANGE", "Orange｜橙色"),
                    ("YELLOW", "Yellow｜黃色"),
                    ("PURPLE", "Purple｜紫色"),
                    ("VIOLET", "Violet｜紫羅蘭色"),
                    ("GREEN", "Green｜綠色"),
                    ("BLUE", "Blue｜藍色"),
                    ("BROWN", "Brown｜褐色"),
                    ("GRAY", "White｜白色"),
                    ("MULTI", "Grey/Black｜灰/黑色"),
                ],
                default="DEFAULT",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DEFAULT", "通用|UNISEX"),
                    ("MALE", "男款|MALE"),
                    ("FEMALE", "女款|FEMALE"),
                ],
                default="DEFAULT",
                max_length=50,
            ),
        ),
    ]
