# Generated by Django 6.0.1 on 2026-03-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0013_product_blood_product_color_product_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DEFAULT", "未指定|UNSPECIFIED"),
                    ("RED", "Red｜紅色"),
                    ("PINK", "Pink｜粉紅色"),
                    ("ORANGE", "Orange｜橙色"),
                    ("YELLOW", "Yellow｜黃色"),
                    ("PURPLE", "Purple｜紫色"),
                    ("VIOLET", "Violet｜紫羅蘭色"),
                    ("GREEN", "Green｜綠色"),
                    ("BLUE", "Blue｜藍色"),
                    ("BROWN", "Brown｜褐色"),
                    ("GRAY", "White｜白色"),
                    ("GREYBLACK", "Grey/Black｜灰/黑色"),
                ],
                default="DEFAULT",
                max_length=50,
            ),
        ),
    ]
