# Generated by Django 6.0.1 on 2026-03-10 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0014_product_is_available_alter_product_color"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="is_available",
            new_name="is_active",
        ),
    ]
