# Generated by Django 6.0.1 on 2026-05-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0015_rename_is_available_product_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_physical",
            field=models.BooleanField(default=True),
        ),
    ]
