# Generated by Django 6.0.1 on 2026-05-11 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0016_product_is_physical"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_voucher",
            field=models.BooleanField(default=False),
        ),
    ]
