# Generated by Django 6.0.1 on 2026-05-11 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0017_product_is_voucher"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="hs_code",
            field=models.CharField(
                blank=True,
                help_text="Harmonized System code for tax/duty (e.g., 9701.10 for paintings)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="tax_category",
            field=models.CharField(
                blank=True,
                help_text="Internal or third-party tax category (e.g., 'physical_art')",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="productvariation",
            name="weight",
            field=models.DecimalField(
                decimal_places=3,
                default=0.0,
                help_text="Weight in kg (e.g., 1.250)",
                max_digits=10,
            ),
        ),
    ]
