# Generated by Django 6.0.1 on 2026-05-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0018_product_hs_code_product_tax_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariation",
            name="weight",
            field=models.PositiveIntegerField(
                default=0, help_text="Weight in g (e.g., 800)"
            ),
        ),
    ]
