# Generated by Django 6.0.1 on 2026-06-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0019_alter_productvariation_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="digital_fulfillment_type",
            field=models.CharField(
                choices=[
                    ("INSTANT", "Instant Auto-Fulfillment ｜ 隨選即發"),
                    ("CUSTOM", "Custom / Manual Processing ｜ 人工交付"),
                ],
                default="INSTANT",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_digital",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="productvariation",
            name="digital_file_path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
