# Generated by Django 6.0.1 on 2026-08-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0021_digitaldownloadtoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="digital_fulfillment_type",
            field=models.CharField(
                choices=[
                    ("INSTANT", "Instant Auto-Fulfillment｜隨選即發"),
                    ("CUSTOM", "Custom / Manual Processing｜人工交付"),
                ],
                default="INSTANT",
                max_length=15,
            ),
        ),
    ]
