# Generated by Django 6.0.1 on 2026-08-24 14:58

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0022_alter_product_digital_fulfillment_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariation",
            name="cancellation_fee_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=5,
                max_length=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(90),
                ],
            ),
        ),
    ]
