# Generated by Django 6.0.1 on 2026-09-11 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creators", "0001_initial"),
        ("store", "0023_productvariation_cancellation_fee_pct"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                help_text="The artisan responsible for this piece. Leave blank for platform-owned items.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="creators.creatorprofile",
            ),
        ),
    ]
