# Generated by Django 6.0.1 on 2026-09-15 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0024_product_creator"),
    ]

    operations = [
        migrations.AddField(
            model_name="productgallery",
            name="gallery_caption",
            field=models.CharField(
                blank=True,
                help_text="Optional poetic caption shown in the gallery lightbox.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="productgallery",
            name="gallery_order",
            field=models.PositiveIntegerField(
                default=0, help_text="Lower numbers appear first. 0 = random order."
            ),
        ),
        migrations.AddField(
            model_name="productgallery",
            name="is_featured_in_gallery",
            field=models.BooleanField(
                default=False,
                help_text="Show this image in the 匠作 Artisans Gallery page.",
            ),
        ),
    ]
