# Generated by Django 6.0.1 on 2026-09-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creators", "0007_remove_creatorprofile_craft_type"),
        ("store", "0025_productgallery_gallery_caption_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="craft_types",
            field=models.ManyToManyField(
                blank=True,
                help_text="Craft disciplines this specific object belongs to.",
                related_name="products",
                to="creators.crafttype",
            ),
        ),
    ]
