# Generated by Django 6.0.1 on 2026-09-23 13:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0006_alter_category_product_format"),
        ("creators", "0009_alter_creatorprofile_tags"),
        ("store", "0027_alter_product_tags"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductReviewLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted for Review｜提交審核"),
                            ("approved", "Approved｜審核通過"),
                            ("rejected", "Rejected｜審核未通過"),
                            ("withdrawn", "Withdrawn｜作者撤回"),
                            ("published", "Published Directly｜直接發布"),
                            ("unpublished", "Unpublished｜下架"),
                        ],
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Product Review Log",
                "verbose_name_plural": "Product Review Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("Draft", "Draft｜草稿"),
                    ("Pending", "Pending Review｜待審核"),
                    ("Published", "Published｜已發布"),
                    ("Rejected", "Rejected｜未通過"),
                    ("Unpublished", "Unpublished｜已下架"),
                ],
                default="Draft",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="submitted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Last time this product was submitted for review.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="productvariation",
            name="cancellation_fee_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(90),
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["creator", "status"], name="store_produ_creator_a51054_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["status", "submitted_at"], name="store_produ_status_ec510d_idx"
            ),
        ),
        migrations.AddField(
            model_name="productreviewlog",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_review_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="productreviewlog",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_logs",
                to="store.product",
            ),
        ),
    ]
