# Generated by Django 6.0.1 on 2026-09-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0028_productreviewlog_product_status_product_submitted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariation",
            name="pending_color",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="productvariation",
            name="pending_size",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="productvariation",
            name="pending_type",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
