# Generated by Django 6.0.1 on 2026-09-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0030_alter_product_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productreviewlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("submitted", "Submitted for Review｜提交審核"),
                    ("approved", "Approved｜審核通過"),
                    ("rejected", "Rejected｜審核未通過"),
                    ("withdrawn", "Withdrawn｜作者撤回"),
                    ("published", "Published Directly｜直接發布"),
                    ("unpublished", "Unpublished｜下架"),
                    ("deactivation_requested", "Deactivation Requested｜申請下架"),
                    ("deletion_approved", "Deletion Approved｜已核准下架"),
                    ("deletion_rejected", "Deletion Declined｜下架請求被拒"),
                ],
                max_length=30,
            ),
        ),
    ]
