# Generated by Django 6.0.1 on 2026-09-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0006_alter_category_product_format"),
        ("creators", "0009_alter_creatorprofile_tags"),
        ("store", "0031_alter_productreviewlog_action"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="product",
            name="store_produ_creator_a51054_idx",
        ),
        migrations.AddField(
            model_name="product",
            name="is_deleted",
            field=models.BooleanField(
                default=False,
                help_text="Soft delete flag. Deleted products are hidden from artisan and storefront views but preserved for audit.",
            ),
        ),
        migrations.AlterField(
            model_name="productreviewlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("submitted", "Submitted for Review｜提交審核"),
                    ("approved", "Approved｜審核通過"),
                    ("rejected", "Rejected｜審核未通過"),
                    ("withdrawn", "Withdrawn｜作者撤回"),
                    ("published", "Published Directly｜直接發布"),
                    ("unpublished", "Unpublished｜下架"),
                    ("deactivation_requested", "Deactivation Requested｜申請下架"),
                    ("deletion_approved", "Deletion Approved｜已核准下架"),
                    ("deletion_rejected", "Deletion Declined｜下架請求被拒"),
                    ("deleted_by_author", "Deleted by Author｜作者刪除"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["creator", "status", "is_deleted"],
                name="store_produ_creator_244750_idx",
            ),
        ),
    ]
