# Generated by Django 6.0.1 on 2026-09-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0032_remove_product_store_produ_creator_a51054_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
    ]
