# Generated by Django 6.0.1 on 2026-09-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0033_alter_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariation",
            name="images",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/products/variations"
            ),
        ),
    ]
