# Generated by Django 6.0.1 on 2026-10-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0007_alter_category_slug"),
        ("creators", "0010_alter_creatorprofile_slug"),
        ("store", "0034_alter_productvariation_images"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(allow_unicode=True),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("product_name",),
                name="unique_active_product_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("slug",),
                name="unique_active_product_slug",
            ),
        ),
    ]
