# Generated by Django 6.0.1 on 2026-10-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0035_alter_product_product_name_alter_product_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(allow_unicode=True, blank=True),
        ),
    ]
