# Generated by Django 6.0.1 on 2026-10-10 13:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creators", "0010_alter_creatorprofile_slug"),
        ("store", "0036_alter_product_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtisanVaultUpload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "staged_filename",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Path relative to XINDENG_VAULT_ROOT/_pending/ for LOCAL and LOCAL_PENDING uploads.",
                        max_length=255,
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The filename the artisan submitted. Preserved for display in the review queue and in download headers.",
                        max_length=255,
                    ),
                ),
                (
                    "file_size",
                    models.PositiveBigIntegerField(
                        default=0,
                        help_text="Bytes. Zero means unknown (EXTERNAL_PENDING pre-copy).",
                    ),
                ),
                (
                    "checksum",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Hex checksum of the file bytes. For LOCAL and LOCAL_PENDING, server-computed SHA-256. For EXTERNAL_PENDING, the artisan-supplied value (may be blank).",
                        max_length=64,
                    ),
                ),
                (
                    "external_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Cloud drive URL provided by the artisan. Only populated for EXTERNAL_PENDING rows; kept after staging for audit.",
                        max_length=500,
                    ),
                ),
                (
                    "storage_kind",
                    models.CharField(
                        choices=[
                            ("LOCAL", "Direct upload to vault staging"),
                            (
                                "EXTERNAL_PENDING",
                                "Cloud drive link awaiting admin copy",
                            ),
                            ("LOCAL_PENDING", "Cloud drive file staged locally"),
                        ],
                        default="LOCAL",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected by admin"),
                            ("SUPERSEDED", "Superseded by newer upload"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "review_note",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Set on rejection; also set on supersession for audit.",
                    ),
                ),
                (
                    "artisan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vault_uploads",
                        to="creators.creatorprofile",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vault_uploads",
                        to="store.product",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vault_uploads_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "variation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vault_uploads",
                        to="store.productvariation",
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "submitted_at"],
                        name="store_artis_status_52fec5_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "PENDING")),
                        fields=("variation",),
                        name="unique_pending_upload_per_variation",
                    )
                ],
            },
        ),
    ]
