# Generated by Django 5.2.7 on 2025-11-17 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0001_initial"),
        ("store", "0007_alter_productvariation_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="product",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="variations",
        ),
        migrations.AddField(
            model_name="cartitem",
            name="product_variation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_sku",
                to="store.productvariation",
            ),
        ),
    ]
