# Generated by Django 5.2.7 on 2025-12-12 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_alter_cart_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipped_from', models.CharField(max_length=100)),
                ('zone', models.CharField(max_length=100)),
                ('service_name', models.CharField(max_length=100)),
                ('min_charge', models.DecimalField(decimal_places=5, default=0.0, max_digits=6)),
                ('min_charge_weight', models.PositiveIntegerField(default=1)),
                ('add_cost_unit_price', models.DecimalField(decimal_places=5, default=0.0, max_digits=6)),
                ('add_cost_weight', models.PositiveIntegerField(default=1)),
                ('other_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('for_small_package', models.BooleanField(default=False)),
                ('is_express', models.BooleanField(default=False)),
                ('is_standard', models.BooleanField(default=False)),
                ('is_economical', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shipping Charge',
                'verbose_name_plural': 'Shipping Charges',
            },
        ),
    ]
