# Generated by Django 5.2.7 on 2025-12-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_shippingcharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingcharge',
            name='add_cost_unit_price',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='shippingcharge',
            name='min_charge',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10),
        ),
    ]
