# Generated by Django 5.2.7 on 2025-12-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_alter_shippingcharge_add_cost_unit_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingcharge',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
