# Generated by Django 5.2.7 on 2026-01-03 06:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_address_label'),
        ('carts', '0009_shippingcharge_country_code_proformainvoice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proformainvoice',
            options={'verbose_name': 'Proforma Invoice', 'verbose_name_plural': 'Proforma Invoices'},
        ),
        migrations.RemoveField(
            model_name='proformainvoice',
            name='item_total',
        ),
        migrations.RemoveField(
            model_name='proformainvoice',
            name='order_total',
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='cart',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carts.cart'),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='cart_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='country',
            field=models.CharField(choices=[('', '請選擇｜Please Choose 🌏'), ('AF', 'Afghanistan 🇦🇫'), ('AX', 'Åland Islands 🇦🇽'), ('AL', 'Albania 🇦🇱'), ('DZ', 'Algeria 🇩🇿'), ('AS', 'American Samoa 🇦🇸'), ('AD', 'Andorra 🇦🇩'), ('AO', 'Angola 🇦🇴'), ('AI', 'Anguilla 🇦🇮'), ('AQ', 'Antarctica 🇦🇶'), ('AG', 'Antigua and Barbuda 🇦🇬'), ('AR', 'Argentina 🇦🇷'), ('AM', 'Armenia 🇦🇲'), ('AW', 'Aruba 🇦🇼'), ('AC', 'Ascension Island 🇦🇨'), ('AU', 'Australia 🇦🇺'), ('AT', 'Austria 🇦🇹'), ('AZ', 'Azerbaijan 🇦🇿'), ('BS', 'Bahamas 🇧🇸'), ('BH', 'Bahrain 🇧🇭'), ('BD', 'Bangladesh 🇧🇩'), ('BB', 'Barbados 🇧🇧'), ('BY', 'Belarus 🇧🇾'), ('BE', 'Belgium 🇧🇯'), ('BZ', 'Belize 🇧🇿'), ('BJ', 'Benin 🇧🇪'), ('BM', 'Bermuda 🇧🇲'), ('BT', 'Bhutan 🇧🇹'), ('BO', 'Bolivia 🇧🇴'), ('BQ', 'Bonaire, Sint Eustatius and Saba 🇧🇶'), ('BA', 'Bosnia and Herzegovina 🇧🇦'), ('BW', 'Botswana 🇧🇼'), ('BV', 'Bouvet Island (Norway) 🇳🇴'), ('BR', 'Brazil 🇧🇷'), ('IO', 'British Indian Ocean Territory 🇮🇴'), ('BN', 'Brunei 🇧🇳'), ('BG', 'Bulgaria 🇧🇬'), ('BF', 'Burkina Faso 🇧🇫'), ('BI', 'Burundi 🇧🇮'), ('CV', 'Cape Verde 🇨🇻'), ('KH', 'Cambodia 🇰🇭'), ('CM', 'Cameroon 🇨🇲'), ('CA', 'Canada 🇨🇦'), ('KY', 'Cayman Islands 🇰🇾'), ('CF', 'Central African Republic 🇨🇫'), ('TD', 'Chad 🇹🇩'), ('CL', 'Chile 🇨🇱'), ('CN', 'China 🇨🇳'), ('CX', 'Christmas Island 🇨🇽'), ('CC', 'Cocos (Keeling) Islands 🇨🇨'), ('CO', 'Colombia 🇨🇴'), ('KM', 'Comoros 🇰🇲'), ('CD', 'Congo (Democratic Republic of the ) 🇨🇩'), ('CG', 'Congo (Republic of the ) 🇨🇬'), ('CK', 'Cook Islands 🇨🇰'), ('CR', 'Costa Rica 🇨🇷'), ('HR', 'Croatia 🇭🇷'), ('CU', 'Cuba 🇨🇺'), ('CW', 'Curaçao (Netherlands Antilles) 🇨🇼'), ('CY', 'Cyprus 🇨🇾'), ('CZ', 'Czech Republic 🇨🇿'), ('CI', "Côte d'Ivoire (Ivory Coast) 🇨🇮"), ('DK', 'Denmark 🇩🇰'), ('DJ', 'Djibouti 🇩🇯'), ('DM', 'Dominica 🇩🇲'), ('DO', 'Dominican Republic 🇩🇴'), ('EC', 'Ecuador 🇪🇨'), ('EG', 'Egypt 🇪🇬'), ('SV', 'El Salvador 🇸🇻'), ('GQ', 'Equatorial Guinea 🇬🇶'), ('ER', 'Eritrea 🇪🇷'), ('EE', 'Estonia 🇪🇪'), ('SZ', 'Eswatini (Swaziland) 🇸🇿'), ('ET', 'Ethiopia 🇪🇹'), ('FK', 'Falkland Islands (Malvinas) 🇫🇰'), ('FO', 'Faroe Islands 🇫🇴'), ('FJ', 'Fiji 🇫🇯'), ('FI', 'Finland 🇫🇮'), ('FR', 'France 🇫🇷'), ('GF', 'French Guiana 🇬🇫'), ('PF', 'French Polynesia 🇵🇫'), ('TF', 'French Southern Territories 🇹🇫'), ('GA', 'Gabon 🇬🇦'), ('GM', 'Gambia 🇬🇲'), ('GE', 'Georgia 🇬🇪'), ('DE', 'Germany 🇩🇪'), ('GH', 'Ghana 🇬🇭'), ('GI', 'Gibraltar 🇬🇮'), ('GR', 'Greece 🇬🇷'), ('GL', 'Greenland 🇬🇱'), ('GD', 'Grenada 🇬🇩'), ('GP', 'Guadeloupe 🇬🇵'), ('GU', 'Guam 🇬🇺'), ('GT', 'Guatemala 🇬🇹'), ('GG', 'Guernsey 🇬🇬'), ('GN', 'Guinea 🇬🇳'), ('GW', 'Guinea-Bissau 🇬🇼'), ('GY', 'Guyana 🇬🇾'), ('HT', 'Haiti 🇭🇹'), ('HT', 'Heard Island and McDonald Islands 🇭🇲'), ('VA', 'Holy See (Vatican City) 🇻🇦'), ('HN', 'Honduras 🇭🇳'), ('HK', 'Hong Kong 🇭🇰'), ('HU', 'Hungary 🇭🇺'), ('IS', 'Iceland 🇮🇸'), ('IN', 'India 🇮🇳'), ('ID', 'Indonesia 🇮🇩'), ('IR', 'Iran 🇮🇷'), ('IQ', 'Iraq 🇮🇶'), ('IE', 'Ireland 🇮🇪'), ('IM', 'Isle of Man 🇮🇲'), ('IL', 'Israel 🇮🇱'), ('IT', 'Italy 🇮🇹'), ('JM', 'Jamaica 🇯🇲'), ('JP', 'Japan 🇯🇵'), ('JE', 'Jersey 🇯🇪'), ('JO', 'Jordan 🇯🇴'), ('KZ', 'Kazakhstan 🇰🇿'), ('KE', 'Kenya 🇰🇪'), ('KI', 'Kiribati 🇰🇮'), ('KW', 'Kuwait 🇰🇼'), ('KG', 'Kyrgyzstan 🇰🇬'), ('LA', 'Laos 🇱🇦'), ('LV', 'Latvia 🇱🇻'), ('LB', 'Lebanon 🇱🇧'), ('LS', 'Lesotho 🇱🇸'), ('LR', 'Liberia 🇱🇷'), ('LY', 'Libya 🇱🇾'), ('LI', 'Liechtenstein 🇱🇮'), ('LT', 'Lithuania 🇱🇹'), ('LU', 'Luxembourg 🇱🇺'), ('MO', 'Macao SAR 🇲🇴'), ('MG', 'Madagascar 🇲🇬'), ('MW', 'Malawi 🇲🇼'), ('MY', 'Malaysia 🇲🇾'), ('MV', 'Maldives 🇲🇻'), ('ML', 'Mali 🇲🇱'), ('MT', 'Malta 🇲🇹'), ('MH', 'Marshall Islands 🇲🇭'), ('MQ', 'Martinique 🇲🇶'), ('MR', 'Mauritania 🇲🇷'), ('MU', 'Mauritius 🇲🇺'), ('YT', 'Mayotte 🇾🇹'), ('MX', 'Mexico 🇲🇽'), ('FM', 'Micronesia 🇫🇲'), ('MD', 'Moldova 🇲🇩'), ('MC', 'Monaco 🇲🇨'), ('MN', 'Mongolia 🇲🇳'), ('ME', 'Montenegro 🇲🇪'), ('MS', 'Montserrat 🇲🇸'), ('MA', 'Morocco 🇲🇦'), ('MZ', 'Mozambique 🇲🇿'), ('MM', 'Myanmar(Burma) 🇲🇲'), ('NA', 'Namibia 🇳🇦'), ('NR', 'Nauru 🇳🇷'), ('NP', 'Nepal 🇳🇵'), ('NL', 'Netherlands 🇳🇱'), ('NC', 'New Caledonia 🇳🇨'), ('NZ', 'New Zealand 🇳🇿'), ('NI', 'Nicaragua 🇳🇮'), ('NE', 'Niger 🇳🇪'), ('NG', 'Nigeria 🇳🇬'), ('NU', 'Niue 🇳🇺'), ('NF', 'Norfolk Island 🇳🇫'), ('MP', 'Northern Mariana Islands 🇲🇵'), ('KP', 'North Korea 🇰🇵'), ('NO', 'Norway 🇳🇴'), ('OM', 'Oman 🇴🇲'), ('PK', 'Pakistan 🇵🇰'), ('PW', 'Palau 🇵🇼'), ('PS', 'Palestine 🇵🇸'), ('PA', 'Panama 🇵🇦'), ('PG', 'Papua New Guinea 🇵🇬'), ('PY', 'Paraguay 🇵🇾'), ('PE', 'Peru 🇵🇪'), ('PH', 'Philippines 🇵🇭'), ('PN', 'Pitcairn Islands 🇵🇳'), ('PL', 'Poland 🇵🇱'), ('PT', 'Portugal 🇵🇹'), ('PR', 'Puerto Rico 🇵🇷'), ('QA', 'Qatar 🇶🇦'), ('MK', 'North Macedonia 🇲🇰'), ('RO', 'Romania 🇷🇴'), ('RU', 'Russia 🇷🇺'), ('RW', 'Rwanda 🇷🇼'), ('RE', 'Reunion Island 🇷🇪'), ('BL', 'Saint Barthelemy 🇧🇱'), ('SH', 'Saint Helena, Ascension and Tristan da Cunha 🇸🇭'), ('KN', 'Saint Kitts and Nevis 🇰🇳'), ('LC', 'Saint Lucia 🇱🇨'), ('MF', 'Saint Martin 🇲🇫'), ('PM', 'Saint Pierre and Miquelon 🇵🇲'), ('VC', 'Saint Vincent and the Grenadines 🇻🇨'), ('WS', 'Samoa 🇼🇸'), ('SM', 'San Marino 🇸🇲'), ('ST', 'Sao Tome and Principe 🇸🇹'), ('SA', 'Saudi Arabia 🇸🇦'), ('SN', 'Senegal 🇸🇳'), ('RS', 'Serbia 🇷🇸'), ('SC', 'Seychelles 🇸🇨'), ('SL', 'Sierra Leone 🇸🇱'), ('SG', 'Singapore 🇸🇬'), ('SX', 'Sint Maarten 🇸🇽'), ('SK', 'Slovakia 🇸🇰'), ('SI', 'Slovenia 🇸🇮'), ('SB', 'Solomon Islands 🇸🇧'), ('SO', 'Somalia 🇸🇴'), ('ZA', 'South Africa 🇿🇦'), ('GS', 'South Georgia and the South Sandwich Islands 🇬🇸'), ('KR', 'South Korea 🇰🇷'), ('SS', 'South Sudan 🇸🇸'), ('ES', 'Spain 🇪🇸'), ('LK', 'Sri Lanka 🇱🇰'), ('SD', 'Sudan 🇸🇩'), ('SR', 'Suriname 🇸🇷'), ('SJ', 'Svalbard and Jan Mayen Islands (Norway) 🇸🇯'), ('SE', 'Sweden 🇸🇪'), ('CH', 'Switzerland 🇨🇭'), ('SY', 'Syria 🇸🇾'), ('TW', 'Taiwan ROC 🇹🇼'), ('TJ', 'Tajikistan 🇹🇯'), ('TZ', 'Tanzania 🇹🇿'), ('TH', 'Thailand 🇹🇭'), ('TL', 'Timor-Leste (East Timor) 🇹🇱'), ('TG', 'Togo 🇹🇬'), ('TK', 'Tokelau 🇹🇰'), ('TO', 'Tonga 🇹🇴'), ('TT', 'Trinidad and Tobago 🇹🇹'), ('TN', 'Tunisia 🇹🇳'), ('TR', 'Turkey 🇹🇷'), ('TM', 'Turkmenistan 🇹🇲'), ('TC', 'Turks and Caicos Islands 🇹🇨'), ('TV', 'Tuvalu 🇹🇻'), ('UG', 'Uganda 🇺🇬'), ('UA', 'Ukraine 🇺🇦'), ('AE', 'United Arab Emirates 🇦🇪'), ('GB', 'United Kingdom 🇬🇧'), ('UM', 'United States Minor Outlying Islands (USMOI) 🇺🇸'), ('US', 'United States 🇺🇸'), ('UY', 'Uruguay 🇺🇾'), ('UZ', 'Uzbekistan 🇺🇿'), ('VU', 'Vanuatu 🇻🇺'), ('VE', 'Venezuela 🇻🇪'), ('VN', 'Vietnam 🇻🇳'), ('VG', 'Virgin Islands (British) 🇻🇬'), ('VI', 'Virgin Islands (US) 🇻🇮'), ('WF', 'Wallis and Futuna 🇼🇫'), ('EH', 'Western Sahara 🇪🇭'), ('YE', 'Yemen 🇦🇪'), ('ZM', 'Zambia 🇿🇲'), ('ZW', 'Zimbabwe 🇿🇼')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='delivery_note',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='do_not_send_invoice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='mobile_area',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='state_province_region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='voucher_applied',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='proformainvoice',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='CheckoutInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('destination_source', models.CharField(choices=[('DEFAULT', 'Default'), ('ADDRESS_BOOK', 'Address Book')], default='DEFAULT', max_length=20)),
                ('default_zone', models.CharField(blank=True, max_length=20, null=True)),
                ('default_destination', models.CharField(blank=True, max_length=100, null=True)),
                ('address_id', models.CharField(blank=True, max_length=5, null=True)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('voucher_applied', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkout_cart', to='carts.cart')),
                ('offer_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.perk')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkout_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
