# Generated by Django 5.2.7 on 2026-01-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0010_alter_proformainvoice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutinfo',
            name='offer_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
