# Generated by Django 5.2.7 on 2026-01-07 06:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0012_rename_is_default_proformainvoice_is_default_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformainvoice',
            name='total_due',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
