# Generated by Django 6.0.1 on 2026-05-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0016_alter_proformainvoice_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkoutinfo",
            name="duty_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="checkoutinfo",
            name="duty_amount_foreign",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="checkoutinfo",
            name="requirements_validated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="checkoutinfo",
            name="tax_calculated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="proformainvoice",
            name="destination_tax_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="proformainvoice",
            name="recipient_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="proformainvoice",
            name="country",
            field=models.CharField(
                choices=[
                    ("AU", "Australia 🇦🇺"),
                    ("HK", "Hong Kong 🇭🇰"),
                    ("ID", "Indonesia 🇮🇩"),
                    ("JP", "Japan 🇯🇵"),
                    ("MO", "Macao SAR 🇲🇴"),
                    ("MY", "Malaysia 🇲🇾"),
                    ("NZ", "New Zealand 🇳🇿"),
                    ("SG", "Singapore 🇸🇬"),
                    ("KR", "South Korea 🇰🇷"),
                    ("TW", "Taiwan ROC 🇹🇼"),
                    ("TH", "Thailand 🇹🇭"),
                ],
                default="",
                max_length=2,
            ),
        ),
    ]
