# Generated by Django 6.0.1 on 2026-05-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0018_alter_proformainvoice_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="proformainvoice",
            name="google_place_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="proformainvoice",
            name="is_verified_by_google",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="proformainvoice",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="proformainvoice",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
