# Generated by Django 6.0.1 on 2026-05-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0020_proformainvoice_gift_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="proformainvoice",
            name="display_mode",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="proformainvoice",
            name="inventory_hold_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="proformainvoice",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PAYPAL", "PayPal Express Checkout"),
                    ("BANK_TRANSFER", "Bank Transfer / WeChat Pay Manual Hold"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
