# Generated by Django 6.0.1 on 2026-06-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "carts",
            "0022_rename_first_name_proformainvoice_recipient_first_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="checkoutinfo",
            name="display_mode",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
