# Generated by Django 6.0.1 on 2026-06-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0023_checkoutinfo_display_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proformainvoice",
            name="country",
            field=models.CharField(
                choices=[
                    ("AU", "Australia 🇦🇺"),
                    ("CN", "China 🇨🇳"),
                    ("HK", "Hong Kong 🇭🇰"),
                    ("JP", "Japan 🇯🇵"),
                    ("MO", "Macao SAR 🇲🇴"),
                    ("MY", "Malaysia 🇲🇾"),
                    ("NZ", "New Zealand 🇳🇿"),
                    ("SG", "Singapore 🇸🇬"),
                    ("KR", "South Korea 🇰🇷"),
                    ("TW", "Taiwan ROC 🇹🇼"),
                    ("XX", "Digital Goods / E-Voucher"),
                ],
                default="",
                max_length=2,
            ),
        ),
    ]
