# Generated by Django 6.0.1 on 2026-06-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0024_alter_proformainvoice_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="proformainvoice",
            name="currency_code",
            field=models.CharField(blank=True, default="USD", max_length=10, null=True),
        ),
    ]
