# Generated by Django 6.0.1 on 2026-06-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0025_proformainvoice_currency_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkoutinfo",
            name="currency_code",
            field=models.CharField(blank=True, default="USD", max_length=10, null=True),
        ),
    ]
