# Generated by Django 6.0.1 on 2026-08-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0026_checkoutinfo_currency_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="proformainvoice",
            name="order_settled",
            field=models.BooleanField(
                default=False,
                help_text="Flips to True once bank/offline payment clears, converting holds to final sales.",
            ),
        ),
    ]
