# Generated by Django 5.2.7 on 2025-11-09 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("first_name", models.CharField(blank=True, max_length=50, null=True)),
                ("last_name", models.CharField(blank=True, max_length=50, null=True)),
                ("username", models.CharField(max_length=50, unique=True)),
                ("email", models.EmailField(max_length=100, unique=True)),
                ("mobile_area", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "mobile_number",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("receive_newsletter", models.BooleanField(default=True)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                ("last_login", models.DateTimeField(auto_now_add=True)),
                ("is_admin", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=False)),
                ("is_superadmin", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address_line_1", models.CharField(blank=True, max_length=100)),
                ("address_line_2", models.CharField(blank=True, max_length=100)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        default="userprofile/default.png",
                        upload_to="userprofile",
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=20)),
                ("state", models.CharField(blank=True, max_length=20)),
                ("country", models.CharField(blank=True, max_length=20)),
                ("zip_code", models.CharField(blank=True, max_length=20)),
                ("dob", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DEFAULT", "♂♀⚥"),
                            ("MALE", "男性 | Male"),
                            ("FEMALE", "女性 | Female"),
                            ("SECRET", "秘密 | Secret"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "blood_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DEFAULT", "🩸"),
                            ("TYPE_A", "A"),
                            ("TYPE_B", "B"),
                            ("TYPE_AB", "AB"),
                            ("TYPE_O", "O"),
                            ("TYPE_OTHER", "其他 | Other"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DEFAULT", "🎨"),
                            ("RED", "紅色 | Red"),
                            ("PINK", "粉色 | Pink"),
                            ("ORANGE", "橙色 | Orange"),
                            ("YELLOW", "黃色 | Yellow"),
                            ("PURPLE", "紫色 | Purple"),
                            ("GREEN", "綠色 | Green"),
                            ("BLUE", "藍色 | Blue"),
                            ("BROWN", "棕色 | Brown"),
                            ("WHITE", "白色 | White"),
                            ("GRAY", "灰色 | Gray"),
                            ("BLACK", "黑色 | Black"),
                            ("OTHER", "其他 | Other"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
