# Generated by Django 5.2.7 on 2025-11-23 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("store", "0008_product_origin"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProductList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "list_type",
                    models.CharField(
                        choices=[
                            ("WISHLIST", "願望清單 | Wishlist"),
                            ("FAVORITE", "收藏清單 | Favorite"),
                        ],
                        max_length=10,
                    ),
                ),
                ("added_date", models.DateTimeField(auto_now_add=True)),
                (
                    "product_variation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variations",
                        to="store.productvariation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_lists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User_Product_List",
                "verbose_name_plural": "User_Product_Lists",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "product_variation", "list_type"),
                        name="unique_user_product_variation_list_constraint",
                    )
                ],
            },
        ),
    ]
