# Generated by Django 5.2.7 on 2025-12-15 09:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_perk_customervoucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='customervoucher',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
