# Generated by Django 5.2.7 on 2025-12-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_customervoucher_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="perk",
            name="featured_image",
            field=models.ImageField(blank=True, null=True, upload_to="perks"),
        ),
    ]
