# Generated by Django 5.2.7 on 2025-12-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_remove_userprofile_address_line_1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="zip_code",
        ),
        migrations.AlterField(
            model_name="address",
            name="label",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HOME", "Home"),
                    ("WORK", "Work"),
                    ("SCHOOL", "School"),
                    ("OTHER", "Other"),
                ],
                default="home",
                max_length=50,
                null=True,
            ),
        ),
    ]
