# Generated by Django 5.2.7 on 2026-01-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_address_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='label',
            field=models.CharField(blank=True, choices=[('home', 'Home'), ('work', 'Work'), ('school', 'School'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
