# Generated by Django 6.0.1 on 2026-03-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_address_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="mobile_area",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="address",
            name="mobile_number",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="address",
            name="recipient_first_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="address",
            name="recipient_last_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
