# Generated by Django 6.0.1 on 2026-03-31 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_alter_address_city_alter_address_country_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPerk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_used", models.BooleanField(default=False)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "unique_code",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                (
                    "perk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.perk"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
