# Generated by Django 6.0.1 on 2026-04-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_userperk"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="china_province",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
