# Generated by Django 6.0.1 on 2026-04-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_address_china_province"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="address_line_1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
