# Generated by Django 6.0.1 on 2026-04-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_alter_chatmessage_receiver"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="content",
            field=models.TextField(max_length=255),
        ),
    ]
