# Generated by Django 6.0.1 on 2026-04-24 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_alter_chatmessage_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="content",
            field=models.TextField(max_length=1000),
        ),
    ]
