# Generated by Django 6.0.1 on 2026-06-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0026_alter_address_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="customervoucher",
            name="failed_pin_attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customervoucher",
            name="is_locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customervoucher",
            name="pin_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customervoucher",
            name="secure_pin",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
