# Generated by Django 6.0.1 on 2026-07-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0027_customervoucher_failed_pin_attempts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customervoucher",
            name="expiry_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
