# Generated by Django 6.0.1 on 2026-08-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0028_customervoucher_expiry_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="perk",
            name="is_member_exclusive",
            field=models.BooleanField(
                default=False,
                help_text="If True, guests cannot apply this code during checkout.",
            ),
        ),
        migrations.AddField(
            model_name="userperk",
            name="is_locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userperk",
            name="locked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userperk",
            name="locked_by_session",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
