# Generated by Django 6.0.1 on 2026-08-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0029_perk_is_member_exclusive_userperk_is_locked_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customervoucher",
            name="locked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customervoucher",
            name="locked_by_session",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
