# Generated by Django 6.0.1 on 2026-09-11 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0030_customervoucher_locked_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="country",
            field=models.CharField(
                choices=[
                    ("", "🌏 Country｜國家/地區"),
                    ("AU", "Australia 🇦🇺"),
                    ("CN", "China 🇨🇳"),
                    ("HK", "Hong Kong 🇭🇰"),
                    ("JP", "Japan 🇯🇵"),
                    ("MO", "Macao SAR 🇲🇴"),
                    ("MY", "Malaysia 🇲🇾"),
                    ("NZ", "New Zealand 🇳🇿"),
                    ("SG", "Singapore 🇸🇬"),
                    ("KR", "South Korea 🇰🇷"),
                    ("TW", "Taiwan ROC 🇹🇼"),
                ],
                default="",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="label",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Label｜標籤🏷️🪹"),
                    ("home", "Home｜家🏠"),
                    ("work", "Work｜工作🏢"),
                    ("school", "School｜學校🏫"),
                    ("other", "Other｜其他🛸"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="blood_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DEFAULT", "🩸"),
                    ("TYPE_A", "A"),
                    ("TYPE_B", "B"),
                    ("TYPE_AB", "AB"),
                    ("TYPE_O", "O"),
                    ("TYPE_OTHER", "Other｜其他"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DEFAULT", "🎨"),
                    ("RED", "Red｜紅色"),
                    ("PINK", "Pink｜粉色"),
                    ("ORANGE", "Orange｜橙色"),
                    ("YELLOW", "Yellow｜黃色"),
                    ("PURPLE", "Purple｜紫色"),
                    ("GREEN", "Green｜綠色"),
                    ("BLUE", "Blue｜藍色"),
                    ("BROWN", "Brown｜棕色"),
                    ("WHITE", "White｜白色"),
                    ("GRAY", "Gray｜灰色"),
                    ("BLACK", "Black｜黑色"),
                    ("OTHER", "Other｜其他"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DEFAULT", "♂♀⚥"),
                    ("MALE", "Male｜男性"),
                    ("FEMALE", "Female｜女性"),
                    ("SECRET", "Secret｜秘密"),
                ],
                max_length=10,
            ),
        ),
    ]
