# Generated by Django 6.0.1 on 2026-10-05 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0032_admintraphit_loginevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="userprofile/"),
        ),
    ]
