# Generated by Django 5.2.7 on 2025-11-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="cat_image",
            field=models.ImageField(blank=True, upload_to="images/categories"),
        ),
    ]
