# Generated by Django 5.2.7 on 2025-11-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0002_alter_category_cat_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "category", "verbose_name_plural": "categories"},
        ),
        migrations.AddField(
            model_name="category",
            name="product_format",
            field=models.CharField(
                blank=True,
                choices=[("physical", "physical"), ("e-product", "e-product")],
                max_length=10,
            ),
        ),
    ]
