# Generated by Django 5.2.7 on 2025-11-09 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0003_alter_category_options_category_product_format"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="product_format",
            field=models.CharField(
                blank=True,
                choices=[("physical", "實物"), ("e-product", "電子產品")],
                max_length=10,
            ),
        ),
    ]
