# Generated by Django 5.2.7 on 2025-11-17 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0004_alter_category_product_format"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="product_format",
            field=models.CharField(
                blank=True,
                choices=[
                    ("physical", "實物 | physical"),
                    ("e-product", "電子產品 | product"),
                ],
                max_length=20,
            ),
        ),
    ]
