# Generated by Django 5.2.7 on 2026-01-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_alter_category_product_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='product_format',
            field=models.CharField(blank=True, choices=[('physical', '實物 | physical'), ('e-product', '電子產品 | product'), ('donation', '捐款 | donation')], max_length=20),
        ),
    ]
