# Generated by Django 6.0.1 on 2026-09-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0006_alter_category_product_format"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(allow_unicode=True, max_length=100, unique=True),
        ),
    ]
