# Generated by Django 5.2.7 on 2025-12-08 11:31

import django.db.models.deletion
import django_ckeditor_5.fields
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, max_length=150, unique=True)),
                ("short_description", models.TextField(max_length=500)),
                (
                    "post_category",
                    models.CharField(
                        choices=[
                            ("Art", "繪畫|Art"),
                            ("Photography", "攝影|Photography"),
                            ("Design", "設計|Design"),
                            ("Music", "音樂|Music"),
                            ("Spirituality", "靈性|Spirituality"),
                            ("Healing", "療癒|Healing"),
                            ("Promotion", "活動|Promotion"),
                            ("Other", "其他|Other"),
                        ],
                        default="Other",
                        max_length=100,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=100)),
                (
                    "featured_image",
                    models.ImageField(upload_to="blog/featured_images/%Y/%m/%d"),
                ),
                (
                    "blog_body",
                    django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
                ),
                (
                    "post_type",
                    models.CharField(
                        choices=[("Blog", "隨筆|Blog"), ("News", "資訊|News")],
                        default="Blog",
                        max_length=100,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("Draft", "Draft"), ("Published", "Published")],
                        default="Draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="author",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
        ),
    ]
