# Generated by Django 6.0.1 on 2026-03-05 13:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="bg_color",
            field=models.CharField(
                blank=True,
                default="#f7f5f5",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid hex color code (e.g., #FFFFFF)",
                        regex="^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$",
                    )
                ],
            ),
        ),
    ]
