# Generated by Django 6.0.1 on 2026-03-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_bg_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_category",
            field=models.CharField(
                choices=[
                    ("Art", "Art｜繪畫"),
                    ("Photography", "Photography｜攝影"),
                    ("Design", "Design｜設計"),
                    ("Music", "Music｜音樂"),
                    ("Spirituality", "Spirituality｜靈性"),
                    ("Healing", "Healing｜療癒"),
                    ("Promotion", "Promotion｜活動"),
                    ("Other", "Other｜其他"),
                ],
                default="Other",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="post_type",
            field=models.CharField(
                choices=[("Blog", "Blog｜隨筆"), ("News", "News｜資訊")],
                default="Blog",
                max_length=100,
            ),
        ),
    ]
