# Generated by Django 6.0.1 on 2026-09-11 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_post_category_alter_post_post_type"),
        ("creators", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                help_text="If authored by an artisan, link to their CreatorProfile. Leave blank for platform-authored posts.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="creators.creatorprofile",
            ),
        ),
    ]
