# Generated by Django 6.0.1 on 2026-09-19 13:22

import django.db.models.deletion
import taggit_selectize.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_post_creator"),
        ("creators", "0008_remove_creatorprofile_wechat_and_more"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="creators.creatorprofile",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[
                    ("Draft", "Draft｜草稿"),
                    ("Pending", "Pending Review｜待審核"),
                    ("Published", "Published｜已發布"),
                    ("Rejected", "Rejected｜未通過"),
                ],
                default="Draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=taggit_selectize.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.CreateModel(
            name="BlogPostReviewLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted for Review｜提交審核"),
                            ("approved", "Approved｜審核通過"),
                            ("rejected", "Rejected｜審核未通過"),
                            ("withdrawn", "Withdrawn｜作者撤回"),
                            ("published", "Published Directly｜直接發布"),
                            ("unpublished", "Unpublished｜下架"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, help_text="Optional comment for this action."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="review_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_logs",
                        to="blog.post",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Post Review Log",
                "verbose_name_plural": "Blog Post Review Logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
