# Generated by Django 6.0.1 on 2026-09-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_post_creator_alter_post_status_alter_post_tags_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[
                    ("Draft", "Draft｜草稿"),
                    ("Pending", "Pending Review｜待審核"),
                    ("Published", "Published｜已發布"),
                    ("Rejected", "Rejected｜未通過"),
                    ("Unpublished", "Unpublished｜已下架"),
                ],
                default="Draft",
                max_length=20,
            ),
        ),
    ]
