# Generated by Django 6.0.1 on 2026-09-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_post_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_deleted",
            field=models.BooleanField(
                default=False,
                help_text="Soft delete flag. Deleted posts are hidden from artisan and public views but preserved for audit.",
            ),
        ),
    ]
