# Generated by Django 6.0.1 on 2026-09-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_post_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpostreviewlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("submitted", "Submitted for Review｜提交審核"),
                    ("approved", "Approved｜審核通過"),
                    ("rejected", "Rejected｜審核未通過"),
                    ("withdrawn", "Withdrawn｜作者撤回"),
                    ("published", "Published Directly｜直接發布"),
                    ("deleted_by_author", "Deleted by Author｜作者刪除"),
                    ("unpublished", "Unpublished｜下架"),
                ],
                max_length=20,
            ),
        ),
    ]
