# Generated by Django 6.0.1 on 2026-10-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_alter_blogpostreviewlog_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="featured_image",
            field=models.ImageField(
                blank=True,
                help_text="Required before submitting for review; optional for drafts. ｜提交審核前為必填；草稿可留空。",
                null=True,
                upload_to="blog/featured_images/%Y/%m/%d",
            ),
        ),
    ]
