# Generated by Django 6.0.1 on 2026-06-27 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("reviews", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="reviews/attachments/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Review Image",
                "verbose_name_plural": "Review Images",
            },
        ),
        migrations.AlterField(
            model_name="comment",
            name="rating",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="comment",
            constraint=models.UniqueConstraint(
                fields=("user", "content_type", "object_id"),
                name="unique_user_generic_review_constraint",
            ),
        ),
        migrations.AddField(
            model_name="commentimage",
            name="comment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="reviews.comment",
            ),
        ),
    ]
