# xindeng/settings.py
"""
Django settings for xindeng project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
from django.core.exceptions import ImproperlyConfigured


load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = os.environ.get("DEBUG", "False").lower() == "true"
DEBUG = os.environ.get("DJANGO_DEBUG", "True").strip() == "True"
print("DEBUG: ", DEBUG)

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '52.62.142.183']

# DJANGO_VITE_DEV_SERVER_HOST = "192.168.1.120"
# X_FRAME_OPTIONS = 'SAMEORIGIN'

# 🌟 THE CORRECT SITE_DOMAIN FORMAT: Full valid URL string prefix used for link rendering.
SITE_DOMAIN = os.environ.get("SITE_DOMAIN", "http://localhost:8000")

# Admin notification email (for review queue, alerts, etc.)
ADMIN_EMAIL = os.environ.get("ADMIN_EMAIL", "gogocfa@yahoo.co.jp")

# Application definition

INSTALLED_APPS = [
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "django_vite",
    "django_password_validators",
    "django_password_validators.password_history",
    "django_htmx",
    "accounts",
    "blog",
    "category",
    "carts",
    "creators",
    "core.apps.CoreConfig",
    "dataentry",
    "emails",
    "orders",
    "store",
    "taggit",
    "taggit_selectize",
    "django_ckeditor_5",
    "django.contrib.humanize",
    "sekizai",
    "reviews",
    "rest_framework",
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google', # Google specific
]

STORAGES = {
    "default": {
        "BACKEND": "core.storage.SafeFileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

SITE_ID = 1 # Matches the ID in the Django Admin 'Sites' section

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Manual Registration
# ACCOUNT_EMAIL_REQUIRED = True # deprecated
# ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']
ACCOUNT_AUTHENTICATION_METHODS = {'email'}
ACCOUNT_EMAIL_VERIFICATION = 'none' # Disable Allauth's manual email verification (since YOU handle it in views.py)
ACCOUNT_CONFIRM_EMAIL_ON_GET = True # Verifies as soon as they click the link

# Google Registration
SOCIALACCOUNT_ADAPTER = 'accounts.adapter.MySocialAccountAdapter'
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_LOGIN_ON_GET = False # Skips the "Are you sure you want to log in?" page
SOCIALACCOUNT_AUTO_SIGNUP = True # Automatically creates account if email is new
SOCIALACCOUNT_EMAIL_VERIFICATION = "none"

LOGIN_REDIRECT_URL = '/accounts/dashboard/main/' 
LOGOUT_REDIRECT_URL = '/accounts/login/'


SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email',],
        'AUTH_PARAMS': {'access_type': 'online',}
    }
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_htmx.middleware.HtmxMiddleware",
    "carts.middleware.CaptureAnonymousSessionMiddleware",
    "carts.middleware.CurrencyMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "xindeng.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "category.context_processors.menu_links",
                "category.context_processors.cart_item_count",
                "sekizai.context_processors.sekizai",
                "blog.context_processors.blog_sidebar",
                "blog.context_processors.blog_review_count",
                "accounts.context_processors.get_google_api",
                "accounts.context_processors.product_review_count",
                # "carts.context_processors.counter",
                # "carts.context_processors.cart_items",
            ],
        },
    },
]

WSGI_APPLICATION = "xindeng.wsgi.application"

ASGI_APPLICATION = "xindeng.asgi.application"

AUTH_USER_MODEL = "accounts.Account"

ADMIN_SECRET_PATH = os.environ.get("ADMIN_SECRET_PATH", "").strip("/")

if not ADMIN_SECRET_PATH:
    # Refuse to start if the secret path is not configured.
    # This is fail-closed: better to crash than to silently expose the admin.
    raise ImproperlyConfigured(
        "ADMIN_SECRET_PATH environment variable is not set. "
        "Add it to your .env file (local) or your deployment environment."
    )

if len(ADMIN_SECRET_PATH) < 12:
    raise ImproperlyConfigured(
        "ADMIN_SECRET_PATH must be at least 12 characters. "
        "Shorter paths are guessable."
    )

if ADMIN_SECRET_PATH.lower() in {"admin", "administrator", "backend", "dashboard", "secret"}:
    raise ImproperlyConfigured(
        "ADMIN_SECRET_PATH is too common. Choose something less guessable."
    )

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators


AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
        "OPTIONS": {
            "user_attributes": ("username", "first_name", "last_name", "email"),
            "max_similarity": 0.7,
        }
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {
            "min_length": 8,
        }
    },
    {
        "NAME": "django_password_validators.password_history.password_validation.UniquePasswordsValidator",
        "OPTIONS": {
             # How many recently entered passwords matter.
             # Passwords out of range are deleted.
             # Default: 0 - All passwords entered by the user. All password hashes are stored.
            "last_passwords": 5 # Only the last 5 passwords entered by the user
        }
    },
    {
        "NAME": "django_password_validators.password_character_requirements.password_validation.PasswordCharacterValidator",
        "OPTIONS": {
             "min_length_digit": 1,
             "min_length_alpha": 1,
             "min_length_special": 1,
             "min_length_lower": 1,
             "min_length_upper": 1,
             "special_characters": "~!@#$%^&*()_+{}\":;'[]"
         }
    },
]

PASSWORD_RESET_TIMEOUT = 86400

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles" # "collectstatic"
STATICFILES_DIRS = [
    BASE_DIR / "assets",
    # BASE_DIR / "media",
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

DJANGO_VITE = {
    "default": {
        "dev_mode": DEBUG,
        "manifest_path": BASE_DIR / "assets" / "manifest.json",
        "dev_server_host": "localhost",
        "dev_server_port": 5173,
        # Ensure this matches your Vite 'base'
        "static_url_prefix": "", 
    }
}

# Media files
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR /"media"

# Messages
from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.INFO: "info",
    messages.SUCCESS: "success",
    messages.WARNING: "warning",
    messages.ERROR: "error",
}

# Email Configuration
EMAIL_HOST = os.environ.get("EMAIL_HOST")
EMAIL_PORT = os.environ.get("EMAIL_PORT")
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL")
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS")

# Tags
TAGGIT_CASE_INSENSITIVE = True

# CKEditor
from .ckeditorconfig import *

# GOOGLE API
GOOGLE_API_KEY = os.environ.get("GOOGLE_API_KEY")

# Ensure Session always exists
# SESSION_SAVE_EVERY_REQUEST = True

# PAYPAL Configuration
PAYPAL_TEST = True
PAYPAL_RECEIVER_EMAIL=os.environ.get("PAYPAL_RECEIVER_EMAIL")

# PAYPAL_CLIENT_ID=os.environ.get("PAYPAL_CLIENT_ID")
# PAYPAL_CLIENT_SECRET=os.environ.get("PAYPAL_CLIENT_SECRET")
PAYPAL_ACCESS_TOKEN=os.environ.get("PAYPAL_ACCESS_TOKEN")

PAYPAL_CLIENT_ID=os.environ.get("PAYPAL_SANDBOX_CLIENT_ID")
PAYPAL_SECRET=os.environ.get("PAYPAL_SANDBOX_CLIENT_SECRET")
PAYPAL_MODE=os.environ.get("PAYPAL_MODE")

SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin-allow-popups'

OPENEXCHANGERATES_APP_ID = os.environ.get("OPENEXCHANGERATES_APP_ID")

# REDIS
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/1',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'CONNECTION_POOL_KWARGS': {
                'max_connections': 50,
                'retry_on_timeout': True,
                'health_check_interval': 30,
            },
        },
    }
}

# CELERY
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL")
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'update-exchange-rates-hourly': {
        'task': 'orders.tasks.update_exchange_rates',
        'schedule': crontab(minute=0),  # ← was: crontab(minute=0, hour=0)
    },
    'check-solar-term-daily': {
        'task': 'accounts.tasks.update_solar_term_broadcast',
        'schedule': crontab(minute=0, hour=0),  # unchanged — daily is correct
    },
    'purge-old-admin-trap-hits-daily': {
        'task': 'accounts.tasks.purge_old_admin_trap_hits',
        'schedule': crontab(minute=30, hour=3),
    },
    'purge-old-login-events-daily': {
        'task': 'accounts.tasks.purge_old_login_events',
        'schedule': crontab(minute=45, hour=3),
    },
}


STRIPE_SECRET_KEY_TEST = os.environ.get("STRIPE_SECRET_KEY_TEST")

# CHANNEL
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}

# ── Bank Transfer / Offline Remittance Details ──
# Per-currency bank accounts. Only HKD and CNY are supported for
# bank-transfer checkout. Each entry's fields are read from the
# environment with the prefix XINDENG_BANK_{CURRENCY}_*.
XINDENG_BANK_ACCOUNTS = {
    "HKD": {
        "bank_name":       os.environ.get("XINDENG_BANK_HKD_BANK_NAME", "[HKD Bank Name]"),
        "account_name":    os.environ.get("XINDENG_BANK_HKD_ACCOUNT_NAME", "[HKD Account Name]"),
        "account_number":  os.environ.get("XINDENG_BANK_HKD_ACCOUNT_NUMBER", "[HKD Account Number]"),
        "swift":           os.environ.get("XINDENG_BANK_HKD_SWIFT", ""),
        "bank_address":    os.environ.get("XINDENG_BANK_HKD_BANK_ADDRESS", ""),
    },
    "CNY": {
        "bank_name":       os.environ.get("XINDENG_BANK_CNY_BANK_NAME", "[CNY Bank Name]"),
        "account_name":    os.environ.get("XINDENG_BANK_CNY_ACCOUNT_NAME", "[CNY Account Name]"),
        "account_number":  os.environ.get("XINDENG_BANK_CNY_ACCOUNT_NUMBER", "[CNY Account Number]"),
        "swift":           os.environ.get("XINDENG_BANK_CNY_SWIFT", ""),
        "bank_address":    os.environ.get("XINDENG_BANK_CNY_BANK_ADDRESS", ""),
    },
}