# Generated by Django 5.2.7 on 2026-01-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('New', 'New'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='payer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
