# Generated by Django 5.2.7 on 2026-01-14 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_order_status_payment_payer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
