# Generated by Django 5.2.7 on 2026-01-22 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0015_proformainvoice_applied_voucher_amount_foreign_and_more'),
        ('orders', '0004_payment_cny_equivalent_payment_currency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='exchange_Rate',
            new_name='exchange_rate',
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carts.proformainvoice'),
        ),
    ]
