# Generated by Django 6.0.1 on 2026-01-31 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_rename_exchange_rate_payment_exchange_rate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("PaypPal", "PayPal"),
                    ("Stripe", "Stripe"),
                    ("AliPay", "AliPay"),
                    ("WeChat", "WeChat"),
                    ("Cash On Delivery", "Cash On Delivery"),
                    ("Credit Card", "Credit Card"),
                    ("Bank Transfer", "Bank Transfer"),
                    ("Mobile Payment", "Mobile Payment"),
                    ("Other", "Other"),
                ],
                default="",
                max_length=100,
            ),
        ),
    ]
