# Generated by Django 6.0.1 on 2026-01-31 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_alter_payment_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="email_sent",
            field=models.BooleanField(default=False),
        ),
    ]
