# Generated by Django 6.0.1 on 2026-05-08 12:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_alter_order_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="destination_tax_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="discount_foreign",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="duty_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="duty_amount_foreign",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="locked_exchange_rate",
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="product_total_foreign",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_cost_foreign",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="tax_foreign",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="total_due_foreign",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="voucher_applied_foreign",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="country",
            field=models.CharField(
                choices=[
                    ("AU", "Australia 🇦🇺"),
                    ("HK", "Hong Kong 🇭🇰"),
                    ("ID", "Indonesia 🇮🇩"),
                    ("JP", "Japan 🇯🇵"),
                    ("MO", "Macao SAR 🇲🇴"),
                    ("MY", "Malaysia 🇲🇾"),
                    ("NZ", "New Zealand 🇳🇿"),
                    ("SG", "Singapore 🇸🇬"),
                    ("KR", "South Korea 🇰🇷"),
                    ("TW", "Taiwan ROC 🇹🇼"),
                    ("TH", "Thailand 🇹🇭"),
                ],
                default="",
                max_length=2,
            ),
        ),
    ]
