# Generated by Django 6.0.1 on 2026-05-11 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_order_destination_tax_id_order_discount_foreign_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="country",
            field=models.CharField(
                choices=[
                    ("AU", "Australia 🇦🇺"),
                    ("HK", "Hong Kong 🇭🇰"),
                    ("JP", "Japan 🇯🇵"),
                    ("MO", "Macao SAR 🇲🇴"),
                    ("MY", "Malaysia 🇲🇾"),
                    ("NZ", "New Zealand 🇳🇿"),
                    ("SG", "Singapore 🇸🇬"),
                    ("KR", "South Korea 🇰🇷"),
                    ("TW", "Taiwan ROC 🇹🇼"),
                    ("TH", "Thailand 🇹🇭"),
                ],
                default="",
                max_length=2,
            ),
        ),
    ]
