# Generated by Django 6.0.1 on 2026-05-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_alter_order_country"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="first_name",
            new_name="recipient_first_name",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="last_name",
            new_name="recipient_last_name",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="mobile_area",
            new_name="recipient_mobile_area",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="mobile_number",
            new_name="recipient_mobile_number",
        ),
        migrations.AlterField(
            model_name="order",
            name="country",
            field=models.CharField(
                choices=[
                    ("AU", "Australia 🇦🇺"),
                    ("CN", "China 🇨🇳"),
                    ("HK", "Hong Kong 🇭🇰"),
                    ("JP", "Japan 🇯🇵"),
                    ("MO", "Macao SAR 🇲🇴"),
                    ("MY", "Malaysia 🇲🇾"),
                    ("NZ", "New Zealand 🇳🇿"),
                    ("SG", "Singapore 🇸🇬"),
                    ("KR", "South Korea 🇰🇷"),
                    ("TW", "Taiwan ROC 🇹🇼"),
                ],
                default="",
                max_length=2,
            ),
        ),
    ]
