# Generated by Django 6.0.1 on 2026-06-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0013_alter_payment_amount_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="ordered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
