# Generated by Django 6.0.1 on 2026-06-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0014_order_ordered_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="inventory_hold_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
