# Generated by Django 6.0.1 on 2026-06-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0016_ordervoucherusage"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="gift_message",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="recipient_email",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
