# Generated by Django 6.0.1 on 2026-06-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0017_order_gift_message_order_recipient_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="currency_code",
            field=models.CharField(blank=True, default="USD", max_length=10, null=True),
        ),
    ]
