# Generated by Django 6.0.1 on 2026-06-16 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0018_order_currency_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_dispatched",
            field=models.BooleanField(default=False),
        ),
    ]
