# Generated by Django 6.0.1 on 2026-06-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0019_order_is_dispatched"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderproduct",
            name="is_dispatched",
            field=models.BooleanField(default=False),
        ),
    ]
