# Generated by Django 6.0.1 on 2026-06-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0020_orderproduct_is_dispatched"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_email_sent",
            field=models.BooleanField(default=False),
        ),
    ]
