# Generated by Django 6.0.1 on 2026-06-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0021_order_payment_email_sent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("Processing", "Processing"),
                    ("Partly_Dispatched", "Partly Dispatched ｜ 部分發貨"),
                    ("All_Dispatched", "All Dispatched ｜ 已全發貨"),
                    ("Shipped", "Shipped"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="New",
                max_length=100,
            ),
        ),
    ]
