# Generated by Django 6.0.1 on 2026-06-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('PayPal', 'PayPal'), ('Stripe', 'Stripe'), ('AliPay', 'AliPay'), ('WeChat', 'WeChat'), ('Cash On Delivery', 'Cash On Delivery'), ('Credit Card', 'Credit Card'), ('Bank Transfer', 'Bank Transfer'), ('Mobile Payment', 'Mobile Payment'), ('Other', 'Other')], default='', max_length=100),
        ),
    ]
