# Generated by Django 6.0.1 on 2026-07-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0024_alter_payment_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("Hold_Pending", "Wait Pending ｜ 待付款"),
                    ("Processing", "Processing ｜ 處理中"),
                    ("Partly_Dispatched", "Partly Dispatched ｜ 部分發貨"),
                    ("All_Dispatched", "All Dispatched ｜ 已全部發貨"),
                    ("Delivered", "Delivered ｜ 已妥投完成"),
                    ("Cancelled", "Cancelled ｜ 已取消"),
                    ("Refunding", "Refunding ｜ 退款處理中"),
                    ("Refunded", "Refunded ｜ 已完成退款"),
                ],
                default="Hold_Pending",
                max_length=100,
            ),
        ),
    ]
