# Generated by Django 6.0.1 on 2026-08-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0028_alter_order_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_note",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
