# Generated by Django 6.0.1 on 2026-08-24 14:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0029_alter_order_delivery_note"),
        ("store", "0023_productvariation_cancellation_fee_pct"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_online_gateway",
            field=models.BooleanField(
                default=True, help_text="True for PayPal/Stripe, False for Bank Wires"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="is_self_service_cancelled",
            field=models.BooleanField(
                default=False,
                help_text="True if done via customer web portal, False if staff-managed",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="net_cash_payout_amount_foreign",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="refund_type",
            field=models.CharField(
                blank=True, help_text="VOUCHER or CASH", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="refund_voucher_id_str",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="restored_voucher_pool_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="total_cancellation_fee_applied",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="user_classification",
            field=models.CharField(
                blank=True, help_text="MEMBER or GUEST", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="orderproduct",
            name="claim_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderproduct",
            name="is_claimed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="orderproduct",
            name="is_partially_used",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="orderproduct",
            name="issued_voucher_uuid",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="currency_code",
            field=models.CharField(default="HKD", max_length=10),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="discount_foreign",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="duty_amount_foreign",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="product_total_foreign",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_cost_foreign",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="tax_foreign",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_due_foreign",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="voucher_applied_foreign",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="orders.order",
            ),
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="store.product"
            ),
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
