# Generated by Django 6.0.1 on 2026-08-27 04:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0030_order_is_online_gateway_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackingNumber",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tracking_code",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Tracking Number / 物流單號",
                    ),
                ),
                (
                    "carrier_name",
                    models.CharField(
                        blank=True,
                        help_text="e.g., SF Express, DHL, etc. / 物流承運商名稱",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_records",
                        to="orders.order",
                    ),
                ),
                (
                    "order_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tracking_assignments",
                        to="orders.orderproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tracking Reference",
                "verbose_name_plural": "Tracking References",
                "ordering": ["-created_at"],
            },
        ),
    ]
