# Generated by Django 6.0.1 on 2026-09-11 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creators", "0001_initial"),
        ("orders", "0031_trackingnumber"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderproduct",
            name="dispatched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderproduct",
            name="fulfilled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fulfilled_lines",
                to="creators.creatorprofile",
            ),
        ),
        migrations.AddField(
            model_name="orderproduct",
            name="fulfillment_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="country",
            field=models.CharField(
                choices=[
                    ("", "🌏 Country｜國家/地區"),
                    ("AU", "Australia 🇦🇺"),
                    ("CN", "China 🇨🇳"),
                    ("HK", "Hong Kong 🇭🇰"),
                    ("JP", "Japan 🇯🇵"),
                    ("MO", "Macao SAR 🇲🇴"),
                    ("MY", "Malaysia 🇲🇾"),
                    ("NZ", "New Zealand 🇳🇿"),
                    ("SG", "Singapore 🇸🇬"),
                    ("KR", "South Korea 🇰🇷"),
                    ("TW", "Taiwan ROC 🇹🇼"),
                ],
                default="",
                max_length=2,
            ),
        ),
    ]
